// Doplnky k receptom prepísaným z kníh/časopisov (import_knihy/*.json) — čo zdroj nemá
// a appka potrebuje: kategória, kuchyňa, popis, tagy, porcie tam, kde ich zdroj nemá číslom,
// a tipy namiesto poznámok pre prepis („treba doplniť").
// Kľúč = `nazov` zo zdrojového JSON-u. Spracúva scripts/import_knihy.js.
"use strict";

// Zdrojový názov suroviny → názov, ktorý sedí na potraviny.json (`najdiPotravinu`).
// p = poznámka navyše, bezMnozstva = do nákupu len ako pripomienka, vsiaknutie = zje sa len časť.
const PREMENUJ = {
  "limeta": { n: "Limetka" },
  "kačacie prsia s kožou (po 150 g)": { n: "Kačacie prsia", p: "s kožou, po 150 g" },
  "omáčka hoisin": { n: "Hoisin omáčka" },
  "pak čoj": { n: "Pak choi" },
  "pasta miso": { n: "Miso pasta" },
  "tuzemák": { n: "Rum", p: "tuzemák" },
  "brusnice namočené v tuzemáku": { n: "Sušené brusnice", p: "namočené v tuzemáku" },
  "posýpka": { n: "Posýpka", bezMnozstva: true },
  "sladká čili omáčka": { n: "Sladká chilli omáčka" },
  "arašidovo-sezamový čili olej": { n: "Sezamový olej", p: "arašidovo-sezamový čili olej" },
  "pomarančová marmeláda": { n: "Marmeláda", p: "pomarančová" },
  "mletá červená paprika": { n: "Mletá sladká paprika" },
  "voda na polentu": { n: "Voda", p: "na polentu" },
  "džem z lesného ovocia": { n: "Džem", p: "z lesného ovocia" },
  "čerešňovica alebo iná ovocná pálenka": { n: "Ovocná pálenka", p: "čerešňovica" },
  "hustá paradajková omáčka": { n: "Passata", p: "hustá paradajková omáčka" },
  "mladá cibuľka": { n: "Jarná cibuľka" },
  "teľacie (hovädzie) líčka": { n: "Hovädzie líčka", p: "alebo teľacie" },
  "hovädzí chvost": { n: "Hovädzí chvost", p: "s kosťou", vsiaknutie: 0.5 },
  "mix syrov Gruyère, Appenzeller, Ementál (strúhaný)": { n: "Strúhaný syr", p: "mix Gruyère, Appenzeller a Ementál" },
  "korenie aleppo ½ ČL alebo údená paprika 1 kopcovitá ČL": { n: "Údená paprika", p: "1 kopcovitá ČL, alebo ½ ČL korenia aleppo" },
  "malé zavárané uhorky, balenie": { n: "Nakladané uhorky", p: "malé, balenie" },
  "zmes húb (šiitake, hliva)": { n: "Huby", p: "šiitake a hliva" },
  "rezance udon hotové": { n: "Udon", p: "hotové rezance" },
  "uvarená šošovica, balenie": { n: "Varená šošovica", p: "balenie" },
  "maslová tekvica – široká časť (po 600 g)": { n: "Maslová tekvica", p: "len široká časť, po 600 g" },
  "nízka roštenka alebo vykostená vysoká roštenka vcelku": { n: "Hovädzia roštenka", p: "nízka alebo vykostená vysoká, vcelku" },
  // mäso s kosťou: do výživy ide len jedlý podiel (USDA refuse), nákup ráta celú váhu
  "bravčové rebrá zadné (1 kus)": { n: "Bravčové rebrá", p: "zadné, 1 kus", vsiaknutie: 0.7 },
  "kuracie krídla malé": { n: "Kuracie krídla", p: "malé", vsiaknutie: 0.55 },
  "kuracie paličky (dolné stehná)": { n: "Kuracie paličky", p: "dolné stehná", vsiaknutie: 0.7 },
  "kuracie stehná veľké s kožou a kosťou": { n: "Kuracie stehná", p: "veľké, s kožou a kosťou", vsiaknutie: 0.8 },
};

const FRITEZA = {
  "Pikantný waleský toast (rarebit)": { kat: "Raňajky", kuch: "Britská", tagy: ["syr", "toast"],
    popis: "Chrumkavý toast z fritézy so syrovo-vaječnou plnkou, horčicou a jalapeňom, k nemu jablkovo-šalátová obloha." },
  "Čili s mäsovými guľkami": { kat: "Hlavné jedlo", kuch: "Mexická", tagy: ["hovädzie", "fazuľa", "vysokobielkovinové"],
    popis: "Hovädzie guľky s limetkou a koriandrom na čiernej fazuli s pečeným batátom a cherry paradajkami — všetko v jednej zásuvke." },
  "Krevetové burgery so sladkou čili omáčkou": { kat: "Hlavné jedlo", kuch: "Ázijská", tagy: ["krevety", "burger"],
    popis: "Krevetové placky so zázvorom a koriandrom v opečenej žemli s jogurtovo-čili omáčkou a chrumkavým šalátom." },
  "Plnené zapečené zemiaky": { kat: "Hlavné jedlo", kuch: "Britská", tagy: ["zemiaky", "fazuľa"],
    popis: "Pečené zemiaky plnené fazuľou v údenej barbecue omáčke, zapečené syrom, so strúhaným zeleninovým šalátom." },
  "Sezamové kuracie guľky": { kat: "Hlavné jedlo", kuch: "Ázijská", tagy: ["kuracie", "rezance"],
    popis: "Kuracie guľky s arašidovým maslom a zázvorom obalené v sezame, na studených ryžových rezancoch so zeleninou a limetkou." },
  "Bravčové rebrá teriyaki": { kat: "Hlavné jedlo", kuch: "Japonská", tagy: ["bravčové", "rebrá"],
    popis: "Mäkké bravčové rebrá pečené nad omáčkou teriyaki a na záver glazované do lepkava.",
    tip: "Podávaj s ryžou a listovým šalátom — výživa je bez prílohy." },
  "Kačka hoisin": { kat: "Hlavné jedlo", kuch: "Čínska", tagy: ["kačka"],
    popis: "Kačacie prsia s chrumkavou kožou a pečenými slivkami, so šalátovými listami, rezancami, zeleninou a omáčkou hoisin." },
  "Falafelové burgery": { kat: "Hlavné jedlo", kuch: "Blízkovýchodná", tagy: ["cícer", "burger"],
    popis: "Cícerové falafelové placky v sezame, v žemli s cesnakovým jogurtom a mrkvovým šalátom." },
  "Barbecue kuracie stehná": { kat: "Hlavné jedlo", kuch: "Ázijská", tagy: ["kuracie"],
    popis: "Kuracie paličky s korením piatich vôní, glazované barbecue omáčkou a obalené v sezamovej strúhanke, s uhorkovo-pomarančovým šalátom." },
  "Paradajkový tart s mozzarellou": { kat: "Hlavné jedlo", kuch: "Francúzska", tagy: ["lístkové cesto"],
    popis: "Obrátený tart z lístkového cesta s pečenými paradajkami, mozzarellou, bazalkou a olivovou zálievkou." },
  "Lepkavé baklažánové rezance": { kat: "Cestoviny", kuch: "Ázijská", tagy: ["baklažán", "rezance"],
    popis: "Baklažán pečený do lepkava so sladkou čili omáčkou, arašidmi a pak choi, premiešaný s rezancami udon." },
  "Lepkavý cibuľový tart": { kat: "Hlavné jedlo", kuch: "Francúzska", tagy: ["lístkové cesto"],
    popis: "Karamelizovaná červená cibuľa s marmeládou a tymianom pod lístkovým cestom, posypaná kozím syrom a orechmi." },
  "Plnené šampiňóny": { kat: "Hlavné jedlo", kuch: "Talianska", tagy: ["huby"],
    popis: "Veľké šampiňóny plnené zemiakmi a syrom taleggio pod rozmarínovou strúhankou, s horkastým listovým šalátom." },
  "Plnená tekvica s čiernou fazuľou": { kat: "Hlavné jedlo", kuch: "Mexická", tagy: ["tekvica", "fazuľa"],
    popis: "Pečená maslová tekvica plnená vajcom, fetou a kuskusom, na čiernej fazuli s avokádom a limetkou." },
  "Najlepšie pečené zemiaky": { kat: "Príloha", kuch: "Britská", tagy: ["zemiaky"],
    popis: "Predvarené zemiaky pečené s maslom, cesnakom a šalviou — zvonka chrumkavé, vnútri mäkké." },
  "Rezancový šalát s opečenými hubami": { kat: "Šalát", kuch: "Ázijská", tagy: ["huby", "rezance"],
    popis: "Hliva a šiitake opečené s rezancami udon v pikantnom zázvorovo-limetkovom dresingu s uhorkou a mätou." },
  "Kurací karí šalát": { kat: "Šalát", kuch: "Britská", tagy: ["kuracie", "karí"],
    popis: "Kuracie stehná pečené v karí paste, natrhané do jogurtu s pečenými broskyňami a cibuľou, na šaláte s mandľami." },
  "Teplý lososový šalát": { kat: "Šalát", kuch: "Francúzska", tagy: ["losos"],
    popis: "Losos pečený na zelenej fazuľke, špargli a šaláte, s vajcom namäkko, opečenou bagetou a paradajkovo-olivovým dresingom." },
  "Luxusné fish & chips": { kat: "Hlavné jedlo", kuch: "Britská", tagy: ["losos", "zemiaky"],
    popis: "Losos v parmezánovej strúhanke so zemiakovými hranolkami, mätovým hráškom a uhorkovou omáčkou." },
  "Rezance s pripečeným bravčovým a ananásom": { kat: "Hlavné jedlo", kuch: "Ázijská", tagy: ["bravčové", "rezance"],
    popis: "Bravčový bôčik a karamelizovaný ananás na ryžových rezancoch s chrumkavou zeleninou, bylinkami a pikantným dresingom." },
  "Šošovica s paprikou a klobásou": { kat: "Hlavné jedlo", kuch: "Stredomorská", tagy: ["šošovica", "klobása"],
    popis: "Pečené papriky a cesnak nasekané so šošovicou a petržlenom, podávané s chrumkavými klobásami." },
  "Pečený medový syr": { kat: "Príloha", kuch: "Stredomorská", porcie: 4, tagy: ["syr", "predjedlo"],
    popis: "Halloumi alebo feta nakrojená do mriežky, potretá medom s korením a zapečená do mäkka.",
    tip: "Ako predjedlo pre 4; s toastom a paradajkovým šalátom s červenou cibuľou a mätou stačí pre 2." },
  "Kuracie krídla miso": { kat: "Hlavné jedlo", kuch: "Japonská", porcie: 2, kcal: 528, tagy: ["kuracie"],
    popis: "Kuracie krídla upečené do chrumkava a glazované misom s medom, posypané sezamom a cibuľkou.",
    tip: "1 porcia = 4 krídla. Kniha uvádza 132 kcal na krídlo." },
  "Lepkavé párkové špízy": { kat: "Príloha", kuch: "Britská", porcie: 4, tagy: ["párky", "párty"],
    popis: "Malé párky so šalviou a pancettou na špáradlách, upečené a na záver pokvapkané medom.",
    tip: "Kniha množstvá neuvádza — tu sú odhadnuté na 12 špízov (2 párky a ½ plátku pancetty na špíz). Vegetariánska verzia: vegetariánske párky bez pancetty.",
    ing: [
      { nazov: "Údená slanina", mnozstvo: 90, jednotka: "g", g_odhad: 90, poznamka: "pancetta, 6 plátkov" },
      { nazov: "Malé párky", mnozstvo: 360, jednotka: "g", g_odhad: 360, poznamka: "24 surových kokteilových" },
      { nazov: "Šalvia", mnozstvo: 12, jednotka: "lístok", g_odhad: 12 },
      { nazov: "Med", mnozstvo: 1, jednotka: "PL", g_odhad: 20, poznamka: "na pokvapkanie" },
    ] },
  "Čedarové trojuholníky s pažítkou": { kat: "Pečivo", kuch: "Britská", tagy: ["syr"],
    popis: "Syrové scones s čedarom a pažítkou, k nim smotanový syr s citrónovou kôrou." },
  "Koláčiky s mentolovou čokoládou": { kat: "Dezert", kuch: "Britská", tagy: ["čokoláda"],
    popis: "Čokoládové koláčiky spájané po dvoch mentolovo-čokoládovou plnkou so smotanovým syrom.",
    tip: "1 porcia = 1 sendvič z 2 koláčikov. Do zásoby: surové guľky 2 dni v chladničke alebo 3 mesiace v mrazničke; upečené 3 dni vo vzduchotesnej nádobe, plnka v chladničke až do skladania." },
};

const FOOD = {
  "Neviditeľný jablkový koláč": { kat: "Dezert", kuch: "Francúzska", porcie: 8, tagy: ["jablká", "jeseň"],
    popis: "Tenučké plátky jabĺk spojené len trochou vláčneho cesta, ktoré sa po upečení medzi jablkami takmer stratí." },
  "Tekvicová polievka s bryndzou": { kat: "Polievka", kuch: "Slovenská", tagy: ["tekvica", "bryndza", "jeseň"],
    popis: "Krémová polievka z neošúpaného hokkaida s pórom a paradajkami, s bryndzou, kyslou smotanou a krutónmi." },
  "Tekvica plnená mletým mäsom": { kat: "Hlavné jedlo", kuch: "Slovenská", porcie: 6, tagy: ["tekvica", "mleté mäso", "jeseň"],
    popis: "Celé hokkaido plnené mletým mäsom s hlivou a paradajkovým pretlakom, zapečené mozzarellou.",
    tip: "Rátaj s hokkaidom okolo 1,2 kg na kus." },
  "Cuketový koláč": { kat: "Raňajky", kuch: "Medzinárodná", tagy: ["cuketa", "slanina", "syr"],
    popis: "Slaný koláč z nastrúhanej cukety a cibule so slaninou a čedarom — dobrý teplý aj studený." },
  "Kuracie prsia v smotanovo-horčicovej omáčke": { kat: "Hlavné jedlo", kuch: "Francúzska", tagy: ["kuracie", "omáčka"],
    popis: "Marinované kuracie prsia opečené a podusené vo vývare so smotanou, horčicou a paprikou.",
    tip: "Čas zahŕňa marinovanie. Hodia sa opekané zemiaky." },
  "Pizzové vafle": { kat: "Raňajky", kuch: "Talianska", porcie: 2, tagy: ["vafle", "syr"],
    popis: "Slané vafle zo syrového cesta s paradajkovou omáčkou a oreganom, ktoré chutia ako pizza.",
    tip: "Z cesta sú 4 vafle, porcia = 2 vafle." },
  "Gaštanovo-čokoládové brownies": { kat: "Dezert", kuch: "Francúzska", porcie: 12, tagy: ["gaštany", "čokoláda"],
    popis: "Vláčne brownies bez múky z horkej čokolády a gaštanového pyré, s celými gaštanmi a mandľami.",
    tip: "Plech 20 × 30 cm, rátané na 12 kociek." },
  "Gaštanový krém": { kat: "Polievka", kuch: "Francúzska", tagy: ["gaštany", "krémová polievka", "jeseň"],
    popis: "Krémová polievka z pečených gaštanov s mrkvou, zemiakom a petržlenom, zjemnená mliekom a maslom.",
    tip: "Časopis teplotu pečenia gaštanov neuvádza — bežne okolo 200 °C, 20–25 min." },
  "Koláče (posvícenské) s tromi plnkami": { nazov: "Posvícenské koláče s tromi plnkami", kat: "Dezert", kuch: "Česká", porcie: 24,
    tagy: ["pečivo", "tvaroh", "mak"],
    popis: "Kysnuté koláčiky z maslového cesta s tvarohovou, jablkovou a makovou plnkou, potreté maslom s tuzemákom.",
    tip: "Z cesta sú 2 plechy (rátané na 24 koláčov). Plnky si môžeš vybrať." },
  "Hovädzí chvost s paprikou": { kat: "Hlavné jedlo", kuch: "Slovenská", tagy: ["hovädzie", "dusené"],
    popis: "Hovädzí chvost pomaly dusený s paprikou, cibuľou, slaninou a novým korením, kým mäso nepadá z kosti." },
  "Pečené hovädzie s yorkshirským pudingom": { kat: "Hlavné jedlo", kuch: "Britská", porcie: 8, tagy: ["hovädzie"],
    popis: "Hovädzia roštenka pečená vcelku na zelenine, s omáčkou z výpeku a červeného vína a nadýchanými yorkshirskými pudingmi.",
    tip: "Mäsa 1,5–2 kg. Z cesta je 12 pudingov; hodí sa hrášok a pečené zemiaky." },
  "Líčka s polentovou kašou": { kat: "Hlavné jedlo", kuch: "Talianska", tagy: ["hovädzie", "dusené"],
    popis: "Hovädzie líčka dusené dve hodiny v červenom víne so zeleninou, podávané na krémovej polente.",
    tip: "Funguje teľacie aj hovädzie líčka. Vodu na polentu odmeraj podľa obalu (okolo 500 ml)." },
  "Zemiakový šterc": { kat: "Hlavné jedlo", kuch: "Slovenská", cas: "40 min", tip: "", tagy: ["zemiaky"],
    popis: "Tradičný šterc z uvarených zemiakov a krupice opraženej na masti, miestami chrumkavý." },
  "Lepenica": { kat: "Hlavné jedlo", kuch: "Slovenská", cas: "40 min", tip: "", tagy: ["zemiaky", "kyslá kapusta"],
    popis: "Roztlačené zemiaky s kyslou kapustou, údenou slaninou a opraženou cibuľou." },
  "Fondue (Švajčiarsko)": { nazov: "Syrové fondue", kat: "Hlavné jedlo", kuch: "Švajčiarska", tagy: ["syr", "alkohol"],
    popis: "Klasické švajčiarske fondue zo syrov gruyère, appenzeller a ementál rozpustených v bielom víne.",
    tip: "Obsahuje alkohol. Pečivo alebo zemiaky na namáčanie kúp zvlášť." },
  "Sladká vínová polievka „Borleves“": { kat: "Dezert", kuch: "Maďarská", tagy: ["alkohol"],
    popis: "Maďarská sladká polievka z bieleho vína so škoricou a klinčekmi, zahustená žĺtkami." },
};

module.exports = { PREMENUJ, FRITEZA, FOOD };
