// TheMealDB — dávka 1 (20 kanonických jedál, bez dezertov).
// `en` + `mealId` nesú atribúciu: importér z nich poskladá `zdroj` a `zdroj_url`.
// Množstvá sú prepočítané z originálu na metrické jednotky a na uvedený počet porcií;
// „cup" originálu sa neprepisuje otrocky (1 cup strúhaného parmezánu nie je 240 g).
// Názvy surovín MUSIA sadnúť na `data/potraviny.json` — inak importér dávku nezapíše.
"use strict";
const i = (nazov, mnozstvo, jednotka, poznamka) => ({ nazov, mnozstvo, jednotka, poznamka: poznamka || "" });

module.exports = [

// ── HOVÄDZIE ──────────────────────────────────────────────────────────────────
{ id:"hovadzie-bourguignon", nazov:"Hovädzie Bourguignon", en:"Beef Bourguignon", mealId:"52904",
  kat:"Hlavné jedlo", kuchyna:"Francúzska", cas:"3 hod 30 min", porcie:4, hlavna:"Hovädzie mäso", narocnost:"náročná",
  popis:"Burgundský klasik: hovädzie dusené v červenom víne so slaninou, šalotkou a hubami. Chce čas, nie zručnosť.",
  ing:[i("Hovädzie mäso",600,"g","na kocky"),i("Slanina",100,"g"),i("Šalotka",350,"g"),i("Šampiňóny",250,"g"),
       i("Cesnak",2,"strúčik"),i("Paradajkový pretlak",1,"PL"),i("Červené víno",400,"ml"),i("Zeler",400,"g","zelerová buľva"),
       i("Olivový olej",2,"PL"),i("Tymian",1,"ČL"),i("Rozmarín",1,"ČL"),i("Bobkový list",2,"ks")],
  postup:["Osuš hovädzie mäso a opeč ho na oleji po dávkach dozlatista — v jednej vrstve, nie na kope, inak sa dusí namiesto pečenia.",
          "Vyber mäso a v tom istom hrnci orestuj slaninu, šalotku a šampiňóny, kým nezhnednú. Pridaj cesnak a paradajkový pretlak a restuj ešte dve minúty.",
          "Vráť mäso do hrnca, zalej červeným vínom a doplň vodou tak, aby mäso vykúkalo nad hladinu. Priveď k varu a zospodu zoškrab pripečenú šťavu.",
          "Prikry a dus v rúre na 150 °C tri hodiny, kým sa mäso nerozpadá.",
          "Olúp zeler, nakrájaj ho na kocky a opeč na olivovom oleji dozlatista. Pridaj tymian, rozmarín a bobkový list, podlej vodou a dus 25 minút domäkka.",
          "Roztlač zeler na hrubé pyré, vyber z neho bylinky a podávaj pod hovädzím."],
  tipy:"Na druhý deň je to lepšie — mäso sa cez noc v omáčke dotiahne. Víno použi také, aké by si aj vypil.",
  tagy:["hovädzie","dusené","francúzska kuchyňa","na víkend","jednohrncové"] },

{ id:"hovadzie-s-brokolicou-wok", nazov:"Hovädzie s brokolicou z woku", en:"Beef and Broccoli Stir-Fry", mealId:"53366",
  kat:"Hlavné jedlo", kuchyna:"Čínska", cas:"30 min", porcie:4, hlavna:"Hovädzia roštenka", narocnost:"jednoduchá",
  popis:"Rýchly wok: marinované plátky roštenky a chrumkavá brokolica v ustricovej omáčke. Na stole za pol hodiny.",
  ing:[i("Hovädzia roštenka",450,"g","na tenké plátky"),i("Brokolica",450,"g"),i("Sójová omáčka",1,"PL"),
       i("Ustricová omáčka",2,"PL"),i("Kukuričný škrob",1.5,"ČL"),i("Hovädzí vývar",60,"ml"),
       i("Rastlinný olej",2,"PL"),i("Cesnak",2,"strúčik","nadrobno"),i("Sherry",1,"ČL")],
  postup:["Nakrájaj roštenku cez vlákno na tenké plátky a zamiešaj ju so sherry, polovicou sójovej omáčky a polovicou škrobu. Nechaj desať minút odstáť.",
          "Rozdeľ brokolicu na ružičky a blanšíruj ju dve minúty vo vriacej vode. Sceď a prepláchni studenou vodou, aby zostala zelená.",
          "Zmiešaj ustricovú omáčku, zvyšnú sójovú omáčku a vývar. Zvyšný škrob rozmiešaj v lyžici studenej vody.",
          "Rozpáľ wok alebo širokú panvicu domodra, nalej olej a rozotri ho po stenách.",
          "Vlož mäso v jednej vrstve a nechaj ho minútu nedotknuté. Obráť, pridaj cesnak a opekaj ďalšiu minútu.",
          "Prilej omáčku aj rozmiešaný škrob, premiešaj do zhustnutia a vmiešaj brokolicu. Podávaj hneď s ryžou."],
  tipy:"Mäso sa krája ľahšie, keď ho dáš na dvadsať minút do mrazničky. Wok musí byť naozaj horúci — vlažná panvica mäso uvarí.",
  tagy:["hovädzie","wok","rýchle","čínska kuchyňa","zelenina"] },

// ── BRAVČOVÉ ──────────────────────────────────────────────────────────────────
{ id:"bigos-polovnicky-gulas", nazov:"Bigos (poľovnícky guláš)", en:"Bigos (Hunters Stew)", mealId:"53018",
  kat:"Hlavné jedlo", kuchyna:"Poľská", cas:"3 hod 30 min", porcie:6, hlavna:"Bravčové plece", narocnost:"stredná",
  popis:"Poľské národné jedlo: kyslá aj sladká kapusta dusená s bravčovým, klobásou a slaninou. Klasické jedlo na jeden veľký hrniec.",
  ing:[i("Slanina",60,"g"),i("Klobása",400,"g","na kolieska"),i("Bravčové plece",450,"g","na kocky"),
       i("Hladká múka",30,"g"),i("Cesnak",3,"strúčik"),i("Cibuľa",150,"g"),i("Šampiňóny",200,"g"),
       i("Kapusta",500,"g","nakrájaná nadrobno"),i("Kyslá kapusta",400,"g"),i("Červené víno",60,"ml"),
       i("Bobkový list",1,"ks"),i("Majoránka",1,"ČL"),i("Mletá paprika",1,"PL"),i("Rasca",0.5,"ČL"),
       i("Hovädzí vývar",800,"ml"),i("Paradajkový pretlak",2,"PL")],
  postup:["Opeč slaninu s klobásou v hrnci, kým slanina nepustí masť. Vyber ich dierovanou lyžicou.",
          "Obaľ kocky bravčového v múke a opeč ich vo vypečenej masti dozlatista. Vyber k slanine.",
          "Orestuj cibuľu, cesnak, šampiňóny a obe kapusty na výpeku asi desať minút — zelenina má zmäknúť, nie zhnednúť.",
          "Zalej červeným vínom a zospodu zoškrab pripečené kúsky. Pridaj bobkový list, majoránku, papriku a rascu a premiešaj.",
          "Vmiešaj paradajkový pretlak a vývar, vráť do hrnca všetko mäso a priveď k varu.",
          "Prikry a dus v rúre na 175 °C dve a pol až tri hodiny, kým sa mäso nerozpadá."],
  tipy:"Bigos sa tradične prehrieva niekoľko dní za sebou a zakaždým je lepší. Ak je kyslá kapusta veľmi ostrá, prepláchni ju studenou vodou.",
  tagy:["bravčové","kapusta","dusené","poľská kuchyňa","jednohrncové","na víkend"] },

{ id:"bryndzove-halusky-mealdb", nazov:"Bryndzové halušky so slaninou", en:"Bryndzové Halušky", mealId:"53190",
  kat:"Hlavné jedlo", kuchyna:"Slovenská", cas:"50 min", porcie:4, hlavna:"Bryndza", narocnost:"stredná",
  popis:"Slovenské národné jedlo tak, ako ho pozná svet: zemiakové halušky, bryndza a vypečená slanina.",
  ing:[i("Zemiak",500,"g"),i("Hladká múka",200,"g"),i("Vajcia",1,"ks"),i("Bryndza",250,"g"),
       i("Slanina",200,"g","na kocky"),i("Pažítka",10,"g")],
  postup:["Nastrúhaj zemiaky najemno aj so šťavou, ktorú pustia.",
          "Zamiešaj do nich múku, vajce a soľ na lepkavé, ale tvarovateľné cesto.",
          "Uvar vo veľkom hrnci osolenú vodu a preteláčaj cesto cez haluškovač priamo do vriacej vody.",
          "Vyber halušky dierovanou lyžicou, keď vyplávajú na hladinu — trvá to dve až tri minúty.",
          "Opeč slaninu na panvici dochrumkava a nechaj ju aj s výpekom bokom.",
          "Zmiešaj horúce halušky s bryndzou, kým sa neobalia do krému, a posyp slaninou a pažítkou."],
  tipy:"Bryndzu rozmiešaj s dvoma lyžicami horúcej vody z haluškov — krém bude hladší a nezrazí sa. Halušky miešaj s bryndzou mimo ohňa.",
  tagy:["bravčové","zemiaky","syr","slovenská kuchyňa","tradičné"] },

// ── RYBY A MORSKÉ PLODY ───────────────────────────────────────────────────────
{ id:"peceny-losos-s-feniklom", nazov:"Pečený losos s feniklom a paradajkami", en:"Baked salmon with fennel & tomatoes", mealId:"52959",
  kat:"Hlavné jedlo", kuchyna:"Britská", cas:"45 min", porcie:2, hlavna:"Losos", narocnost:"jednoduchá",
  popis:"Jedna zapekacia misa, tri suroviny a pätnásť minút v rúre. Fenikel pod lososom zmäkne a nasaje šťavu.",
  ing:[i("Feniklová hľuza",400,"g"),i("Petržlen",10,"g","nasekaný"),i("Citrón",1,"ks"),
       i("Cherry paradajky",175,"g"),i("Olivový olej",1,"PL"),i("Losos",350,"g","filety"),i("Olivy",40,"g","čierne")],
  postup:["Odrež feniklovej hľuze vňať a odlož ju. Buľvu prekroj a nakrájaj na kliny.",
          "Uvar fenikel desať minút v osolenej vode a dobre sceď.",
          "Nasekaj feniklovú vňať a zmiešaj ju s petržlenom a nastrúhanou citrónovou kôrou.",
          "Rozlož fenikel do zapekacej misy, pridaj paradajky, pokvapkaj olivovým olejom a peč desať minút na 180 °C.",
          "Vlož medzi zeleninu filety lososa, pokvapkaj citrónovou šťavou a peč ďalších pätnásť minút.",
          "Posyp bylinkovou zmesou, rozhoď po vrchu olivy a podávaj rovno z misy."],
  tipy:"Losos je hotový, keď sa dá vidličkou ľahko rozdeliť na plátky — pár minút navyše ho vysuší.",
  tagy:["ryba","pečené","zelenina","rýchle","jedna misa"] },

// ── BEZMÄSITÉ ─────────────────────────────────────────────────────────────────
{ id:"baingan-bharta", nazov:"Baingan bharta (indický baklažán)", en:"Baingan Bharta", mealId:"52807",
  kat:"Hlavné jedlo", kuchyna:"Indická", cas:"45 min", porcie:3, hlavna:"Baklažán", narocnost:"stredná",
  popis:"Baklažán opečený nad plameňom, olúpaný a rozmiaknutý s cibuľou a paradajkami. Dymová chuť je celé tajomstvo.",
  ing:[i("Baklažán",500,"g"),i("Cibuľa",120,"g","nadrobno"),i("Paradajky",240,"g"),
       i("Cesnak",6,"strúčik"),i("Chilli paprička",1,"ks"),i("Chilli mleté",0.25,"ČL"),
       i("Rastlinný olej",1.5,"PL"),i("Koriandrová vňať",10,"g")],
  postup:["Potri baklažán olejom a opeč ho celý nad plameňom alebo v rúre, kým koža nesčernie a dužina nezmäkne.",
          "Vlož horúci baklažán do misy so studenou vodou, nechaj vychladnúť a olúp z neho spálenú kožu.",
          "Nasekaj dužinu nadrobno alebo ju roztlač vidličkou.",
          "Rozohrej olej a orestuj cibuľu s cesnakom dosklovita — nesmú zhnednúť.",
          "Pridaj nasekanú chilli papričku a po minúte paradajky. Restuj, kým sa olej neoddelí od zmesi.",
          "Vmiešaj mleté chilli a baklažán, dus päť minút a nakoniec vmiešaj koriandrovú vňať."],
  tipy:"Bez opečenia nad otvoreným plameňom stratíš dymovú chuť, kvôli ktorej sa jedlo robí. Plynový sporák alebo gril sú lepšie než rúra.",
  tagy:["bezmäsité","baklažán","indická kuchyňa","zelenina"] },

{ id:"borsc-repna-polievka", nazov:"Boršč (repná polievka)", en:"Beetroot Soup (Borscht)", mealId:"53078",
  kat:"Polievka", kuchyna:"Ukrajinská", cas:"40 min", porcie:4, hlavna:"Červená repa", narocnost:"jednoduchá",
  popis:"Ukrajinská repná polievka s fazuľou a zemiakmi. Sýta natoľko, že obed netreba dopĺňať.",
  ing:[i("Červená repa",500,"g","na kocky"),i("Olivový olej",4,"PL"),i("Zeleninový vývar",1400,"ml"),
       i("Zemiak",400,"g","na kocky"),i("Biele fazule",240,"g","z konzervy"),i("Kôpor",10,"g")],
  postup:["Olúp červenú repu a nakrájaj ju na kocky.",
          "Zalej repu vývarom a var pätnásť minút.",
          "Pridaj zemiaky a olivový olej a var ďalších pätnásť minút, kým zemiaky nezmäknú.",
          "Vmiešaj scedené fazule a nechaj polievku prejsť varom ešte päť minút.",
          "Posyp nasekaným kôprom a podávaj rovno z hrnca."],
  tipy:"Kvapka octu alebo citrónovej šťavy na konci udrží farbu jasne červenú — bez nej repa do hneda vybledne.",
  tagy:["polievka","bezmäsité","strukoviny","zelenina","lacné"] },

{ id:"sci-kapustova-polievka", nazov:"Šči (kapustová polievka)", en:"Cabbage Soup (Shchi)", mealId:"53077",
  kat:"Polievka", kuchyna:"Ruská", cas:"50 min", porcie:6, hlavna:"Kapusta", narocnost:"jednoduchá",
  popis:"Ruská kapustová polievka so zeleninou a zemiakmi, dochutená kyslou smotanou a kôprom.",
  ing:[i("Maslo",45,"g"),i("Cibuľa",150,"g"),i("Kapusta",700,"g","nakrájaná nadrobno"),
       i("Mrkva",80,"g"),i("Zeler",60,"g"),i("Bobkový list",1,"ks"),i("Zeleninový vývar",1900,"ml"),
       i("Zemiak",350,"g","na kocky"),i("Paradajky",250,"g"),i("Kyslá smotana",120,"g"),i("Kôpor",10,"g")],
  postup:["Rozpusti maslo v hrnci a orestuj cibuľu dosklovita.",
          "Pridaj kapustu, mrkvu a zeler a restuj tri minúty, kým zelenina nezačne mäknúť.",
          "Prilej vývar, vlož bobkový list a var pätnásť minút pod pokrievkou.",
          "Vlož zemiaky a var ďalších desať minút domäkka.",
          "Pridaj nakrájané paradajky a var odkryté päť minút. Dochuť soľou a korením.",
          "Vyber bobkový list a podávaj s lyžicou kyslej smotany a kôprom."],
  tipy:"Šči sa v Rusku tradične nechá cez noc odstáť a až potom sa zohreje — kapusta zjemnie a chute sa spoja.",
  tagy:["polievka","bezmäsité","kapusta","zelenina","lacné"] },

{ id:"cicerove-fajitas", nazov:"Cícerové fajitas", en:"Chickpea Fajitas", mealId:"52870",
  kat:"Hlavné jedlo", kuchyna:"Mexická", cas:"35 min", porcie:4, hlavna:"Cícer", narocnost:"jednoduchá",
  popis:"Chrumkavo upečený cícer namiesto mäsa, k tomu guacamole, nakladaná cibuľa a harissová smotana.",
  ing:[i("Cícer",400,"g","scedený"),i("Olivový olej",1,"PL"),i("Mletá paprika",1,"ČL"),
       i("Paradajky",200,"g"),i("Cibuľa",100,"g","červená, na tenké plátky"),i("Ocot",2,"ČL","červený vínny"),
       i("Avokádo",1,"ks"),i("Limetka",1,"ks"),i("Kyslá smotana",100,"g"),i("Harissa",2,"ČL"),
       i("Tortilla",4,"ks"),i("Koriandrová vňať",10,"g")],
  postup:["Osuš scedený cícer, zamiešaj ho s olejom a mletou paprikou a rozlož na plech.",
          "Peč cícer na 200 °C dvadsať až dvadsaťpäť minút dochrumkava; v polovici plech pretras.",
          "Zmiešaj nakrájané paradajky a cibuľu s octom a nechaj ich zatiaľ naložiť.",
          "Roztlač avokádo vidličkou nahrubo, zamiešaj doň limetkovú šťavu a osoľ.",
          "Rozmiešaj kyslú smotanu s harissou.",
          "Opeč tortilly na suchej panvici z oboch strán a naplň ich smotanou, cícerom, guacamole, naloženou zeleninou a koriandrom."],
  tipy:"Cícer musí byť pred pečením naozaj suchý — vlhký sa upečie mäkký, nie chrumkavý.",
  tagy:["bezmäsité","strukoviny","mexická kuchyňa","tortilla","rýchle"] },

// ── JAHŇACIE ──────────────────────────────────────────────────────────────────
{ id:"adana-kebab", nazov:"Adana kebab", en:"Adana kebab", mealId:"53262",
  kat:"Hlavné jedlo", kuchyna:"Turecká", cas:"40 min", porcie:4, hlavna:"Jahňacie mäso", narocnost:"stredná",
  popis:"Turecký grilovaný kebab z mletého jahňacieho s paprikovou pastou a chilli vločkami.",
  ing:[i("Mleté jahňacie stehno",700,"g"),i("Kapia",300,"g"),i("Ajvar",3,"PL"),
       i("Chilli vločky",1,"PL"),i("Slnečnicový olej",3,"PL")],
  postup:["Nasekaj kapiu najemno a vytlač z nej v site čo najviac šťavy — mokrá zmes sa na ihle neudrží.",
          "Zmiešaj mäso s kapiou, ajvarom, chilli vločkami, soľou a dvoma lyžicami oleja.",
          "Miesi zmes aspoň tri minúty, kým nezačne byť lepkavá. Ruky si priebežne namáčaj v studenej vode.",
          "Prikry misu a vychlaď zmes v chladničke aspoň dve hodiny.",
          "Rozdeľ zmes na osem dielov a vytvaruj z nich okolo ihiel dvadsaťcentimetrové valce. Mokrými prstami sprav po dĺžke priehlbiny.",
          "Griluj kebaby desať až dvanásť minút a priebežne ich otáčaj, kým nie sú zvonka chrumkavé."],
  tipy:"Bez vychladenia sa zmes z ihiel zošmykne. Ak nemáš ihly, vytvaruj podlhovasté fašírky a upeč ich na plechu pri 220 °C.",
  tagy:["jahňacie","grilované","turecká kuchyňa","mleté mäso"] },

{ id:"jahnacie-souvlaki", nazov:"Jahňacie souvlaki s citrónom", en:"Lamb and Lemon Souvlaki", mealId:"53009",
  kat:"Hlavné jedlo", kuchyna:"Grécka", cas:"30 min", porcie:4, hlavna:"Jahňacie stehno", narocnost:"jednoduchá",
  popis:"Grécke špízy z jahňacieho marinovaného v citróne, cesnaku a kôpre. Marináda robí všetku prácu.",
  ing:[i("Cesnak",2,"strúčik"),i("Olivový olej",4,"PL"),i("Citrón",1,"ks"),
       i("Kôpor",5,"g"),i("Jahňacie stehno",750,"g","na kocky"),i("Pita",4,"ks")],
  postup:["Roztlač cesnak so soľou na hladkú pastu.",
          "Rozšľahaj olivový olej s citrónovou šťavou, nastrúhanou kôrou, nasekaným kôprom a cesnakovou pastou.",
          "Zamiešaj do marinády kocky jahňacieho, prikry a marinuj aspoň dve hodiny, pokojne cez noc.",
          "Vyber mäso z chladničky pol hodiny pred grilovaním a napichaj ho na ihly.",
          "Griluj špízy na vysokom ohni dve až tri minúty z každej strany a priebežne ich potieraj zvyšnou marinádou.",
          "Zohrej pity a naplň ich mäsom zo špízov."],
  tipy:"Drevené ihly namoč pred použitím na pol hodinu do vody, inak na grile zhoria.",
  tagy:["jahňacie","grilované","grécka kuchyňa","marinované"] },

{ id:"jahnacie-biryani", nazov:"Jahňacie biryani", en:"Lamb Biryani", mealId:"52805",
  kat:"Hlavné jedlo", kuchyna:"Indická", cas:"2 hod", porcie:6, hlavna:"Jahňacie stehno", narocnost:"náročná",
  popis:"Vrstvené indické biryani: dusené jahňacie pod ryžou basmati, šafranom a smaženou cibuľou.",
  ing:[i("Kešu",60,"g"),i("Mak",5,"g"),i("Rasca rímska",10,"g"),i("Cibuľa",300,"g","na tenké plátky"),
       i("Zázvor",10,"g"),i("Cesnak",4,"strúčik"),i("Mäta",5,"g"),i("Koriandrová vňať",10,"g"),
       i("Šafran",0.5,"ČL"),i("Ghí",2,"PL"),i("Ryža basmati",400,"g"),i("Biely jogurt",120,"g"),
       i("Bobkový list",1,"ks"),i("Škorica",1,"ČL"),i("Klinčeky",3,"ks"),i("Kardamóm",2,"ks"),
       i("Jahňacie stehno",450,"g","na kocky"),i("Chilli mleté",1,"ČL"),i("Garam masala",1,"PL")],
  postup:["Pomeľ kešu, mak a polovicu rímskej rasce s trochou vody na hladkú pastu.",
          "Opraž cibuľu na ghí dozlatista a nechaj ju odkvapkať na papierovej utierke — pri chladnutí zchrumkavie.",
          "Opláchni ryžu a nechaj ju dvadsať minút napučať vo vode.",
          "Orestuj v hrnci zázvor a cesnak, pridaj orechovú pastu, chilli, garam masalu, mätu a koriander a restuj dve minúty.",
          "Vmiešaj jogurt mimo ohňa, aby sa nezrazil, pridaj jahňacie a soľ, podlej vodou a dus hodinu pod pokrievkou domäkka.",
          "Uvar ryžu v hojnej osolenej vode s bobkovým listom, škoricou, klinčekmi a kardamónom len sedem minút a sceď ju — má byť na osemdesiat percent hotová.",
          "Urovnaj mäso na dne hrnca, navrstvi naň ryžu, posyp smaženou cibuľou a pokvapkaj šafranom rozpusteným v troche teplej vody.",
          "Prikry a dopeč pätnásť minút na 175 °C. Premiešaj až na tanieri."],
  tipy:"Ryža sa dovarí parou od mäsa — ak ju uvaríš domäkka hneď, biryani sa zmení na kašu.",
  tagy:["jahňacie","ryža","indická kuchyňa","na víkend","vrstvené"] },

// ── CESTOVINY ─────────────────────────────────────────────────────────────────
{ id:"fettuccine-alfredo", nazov:"Fettuccine Alfredo", en:"Fettuccine Alfredo", mealId:"53064",
  kat:"Cestoviny", kuchyna:"Talianska", cas:"20 min", porcie:4, hlavna:"Fettuccine", narocnost:"jednoduchá",
  popis:"Tri suroviny, dvadsať minút: cestoviny, maslo a parmezán v smotanovej omáčke.",
  ing:[i("Fettuccine",400,"g"),i("Smotana na šľahanie",120,"ml"),i("Maslo",80,"g"),
       i("Parmezán",80,"g","nastrúhaný"),i("Petržlen",10,"g","nasekaný")],
  postup:["Uvar fettuccine v osolenej vode podľa návodu na obale a odlož si hrnček vody z varenia.",
          "Rozohrej na širokej panvici smotanu s maslom, kým sa maslo nerozpustí a smotana nezačne bublať.",
          "Vmiešaj metličkou nastrúhaný parmezán a dochuť soľou a čerstvo mletým korením.",
          "Pridaj scedené cestoviny a premiešaj ich s omáčkou; podľa potreby prilej vodu z varenia, kým sa omáčka neprilepí na cestoviny.",
          "Posyp petržlenom a podávaj hneď."],
  tipy:"Voda z varenia cestovín je to, čo omáčku spojí — bez nej sa parmezán zrazí do hrudiek. Panvicu pri miešaní stiahni z ohňa.",
  tagy:["cestoviny","syr","rýchle","talianska kuchyňa","bezmäsité"] },

{ id:"linguine-s-krevetami-a-chilli", nazov:"Linguine s krevetami a chilli", en:"Chilli prawn linguine", mealId:"52839",
  kat:"Cestoviny", kuchyna:"Talianska", cas:"25 min", porcie:4, hlavna:"Krevety", narocnost:"jednoduchá",
  popis:"Cestoviny s krevetami, cesnakom a chilli, odľahčené cukrovým hráškom a cherry paradajkami.",
  ing:[i("Linguine",280,"g"),i("Cukrový hrášok",200,"g"),i("Olivový olej",2,"PL"),
       i("Cesnak",2,"strúčik","nasekaný"),i("Chilli paprička",1,"ks"),i("Krevety",300,"g","olúpané"),
       i("Cherry paradajky",180,"g","prekrojené"),i("Bazalka",5,"g"),i("Limetka",1,"ks"),i("Krupicový cukor",2,"ČL")],
  postup:["Uvar linguine v osolenej vode podľa obalu a poslednú minútu k nim prihoď cukrový hrášok.",
          "Rozohrej olivový olej a restuj na miernom ohni cesnak s nakrájanou chilli papričkou pol minúty — cesnak nesmie zhnednúť.",
          "Vlož krevety a opekaj ich na vyššom ohni asi tri minúty, kým neružovejú.",
          "Pridaj prekrojené cherry paradajky a nechaj ich len prehriať, aby sa nerozpadli.",
          "Zamiešaj scedené cestoviny s hráškom do panvice a dochuť limetkovou šťavou, cukrom a soľou.",
          "Natrhaj do nich bazalku a podávaj hneď."],
  tipy:"Krevety sú hotové, keď sa stočia do písmena C. Keď sa stočia do O, sú prepečené a tuhé.",
  tagy:["cestoviny","morské plody","rýchle","talianska kuchyňa","chilli"] },

// ── RAŇAJKY ───────────────────────────────────────────────────────────────────
{ id:"chlebova-omeleta", nazov:"Chlebová omeleta", en:"Bread omelette", mealId:"53076",
  kat:"Raňajky", kuchyna:"Indická", cas:"15 min", porcie:2, hlavna:"Vajcia", narocnost:"jednoduchá",
  popis:"Indické pouličné raňajky: toastový chlieb zapečený vo vajci s cibuľou a chilli.",
  ing:[i("Toastový chlieb",4,"plátok"),i("Vajcia",3,"ks"),i("Cibuľa",60,"g","nadrobno"),
       i("Chilli paprička",1,"ks","nadrobno"),i("Koriandrová vňať",5,"g"),i("Rastlinný olej",1,"PL")],
  postup:["Rozšľahaj vajcia so soľou, nasekanou cibuľou, chilli papričkou a koriandrom.",
          "Rozohrej na panvici olej a nalej naň polovicu vaječnej zmesi.",
          "Vlož do ešte tekutej zmesi dva plátky chleba vedľa seba a jemne ich pritlač, nech sa obalia.",
          "Opeč omeletu dve minúty, potom ju obráť aj s chlebom a dopeč z druhej strany dozlatista.",
          "Zopakuj to so zvyškom zmesi a chleba a podávaj horúce."],
  tipy:"Chlieb pritlač do vajca hneď, kým je zmes tekutá — na zapečenej omelete sa už neudrží.",
  tagy:["raňajky","vajcia","rýchle","indická kuchyňa"] },

{ id:"ranajkove-zemiaky", nazov:"Raňajkové zemiaky s paprikou", en:"Breakfast Potatoes", mealId:"52965",
  kat:"Raňajky", kuchyna:"Kanadská", cas:"40 min", porcie:4, hlavna:"Zemiak", narocnost:"jednoduchá",
  popis:"Zemiaky na kocky opečené dochrumkava s cibuľou a paprikou. Klasická príloha k raňajkovým vajciam.",
  ing:[i("Zemiak",700,"g","na kocky"),i("Cibuľa",120,"g"),i("Kapia",120,"g"),
       i("Olivový olej",2,"PL"),i("Mletá paprika",1,"ČL"),i("Pažítka",10,"g")],
  postup:["Nakrájaj zemiaky na rovnaké dvojcentimetrové kocky a osuš ich v utierke.",
          "Zamiešaj zemiaky s olejom, mletou paprikou a soľou a rozlož ich na plech v jednej vrstve.",
          "Peč na 220 °C dvadsať minút, kým nezačnú zlatnúť.",
          "Pridaj nakrájanú cibuľu a kapiu, premiešaj a peč ďalších pätnásť minút.",
          "Posyp nasekanou pažítkou a podávaj horúce."],
  tipy:"Zemiaky rozlož na plechu tak, aby sa nedotýkali — na kope sa uparia a chrumkavé nebudú.",
  tagy:["raňajky","zemiaky","pečené","bezmäsité","príloha"] },

// ── POLIEVKY ──────────────────────────────────────────────────────────────────
{ id:"brokolicova-polievka-s-nivou", nazov:"Brokolicová polievka s nivou", en:"Broccoli & Stilton soup", mealId:"52842",
  kat:"Polievka", kuchyna:"Britská", cas:"35 min", porcie:4, hlavna:"Brokolica", narocnost:"jednoduchá",
  popis:"Britská klasika: hustá brokolicová polievka, ktorej niva dodá slanú hĺbku.",
  ing:[i("Maslo",30,"g"),i("Cibuľa",120,"g"),i("Zeler",100,"g"),i("Pór",100,"g"),
       i("Zemiak",200,"g"),i("Zeleninový vývar",1200,"ml"),i("Brokolica",400,"g"),i("Niva",140,"g")],
  postup:["Rozpusti maslo v hrnci a orestuj cibuľu, zeler a pór asi päť minút domäkka.",
          "Pridaj nakrájané zemiaky, zalej vývarom a var pätnásť minút.",
          "Vlož ružičky brokolice a var ďalších päť až sedem minút — brokolica má byť práve mäkká, nie rozvarená.",
          "Rozmixuj polievku dohladka ponorným mixérom.",
          "Vmiešaj nadrobenú nivu a miešaj, kým sa nerozpustí. Dochuť korením; soľ pridávaj až nakoniec, syr je slaný."],
  tipy:"Brokolicu nevar dlhšie, než treba — po siedmich minútach začne polievka šednúť.",
  tagy:["polievka","bezmäsité","syr","zelenina","britská kuchyňa"] },

{ id:"smotanova-paradajkova-polievka", nazov:"Smotanová paradajková polievka", en:"Creamy Tomato Soup", mealId:"52841",
  kat:"Polievka", kuchyna:"Britská", cas:"40 min", porcie:4, hlavna:"Paradajky", narocnost:"jednoduchá",
  popis:"Hustá paradajková polievka so smotanou a bazalkou. Základná výbava chladného dňa.",
  ing:[i("Paradajky",800,"g"),i("Cibuľa",120,"g"),i("Cesnak",2,"strúčik"),i("Olivový olej",2,"PL"),
       i("Zeleninový vývar",600,"ml"),i("Smotana na varenie",100,"ml"),i("Bazalka",5,"g"),i("Krupicový cukor",1,"ČL")],
  postup:["Orestuj cibuľu na olivovom oleji domäkka, asi osem minút.",
          "Pridaj cesnak a restuj ešte minútu, aby nezhnedol.",
          "Vsyp nakrájané paradajky, zalej vývarom a var dvadsať minút.",
          "Rozmixuj polievku dohladka a podľa chuti ju preceď cez sitko.",
          "Vmiešaj smotanu a cukor, ktorý zrazí kyslosť paradajok, a dochuť soľou a korením.",
          "Natrhaj do polievky bazalku tesne pred podávaním."],
  tipy:"Lyžička cukru nie je na sladkosť, ale na vyváženie kyslosti paradajok — bez nej polievka rezne.",
  tagy:["polievka","bezmäsité","paradajky","lacné","britská kuchyňa"] },

// ── NÁTIERKA ──────────────────────────────────────────────────────────────────
{ id:"baba-ghanoush", nazov:"Baba ghanoush", en:"Baba Ghanoush", mealId:"53094",
  kat:"Nátierka", kuchyna:"Blízkovýchodná", cas:"45 min", porcie:4, hlavna:"Baklažán", narocnost:"jednoduchá",
  popis:"Sýrska nátierka z pečeného baklažánu s tahini, cesnakom a citrónom.",
  ing:[i("Baklažán",700,"g"),i("Tahini",60,"g"),i("Cesnak",2,"strúčik"),
       i("Citrón",1,"ks"),i("Olivový olej",2,"PL"),i("Rasca rímska",0.5,"ČL"),i("Petržlen",5,"g")],
  postup:["Popichaj baklažány vidličkou a peč ich celé na 220 °C štyridsať minút, kým sa koža neodlepí a dužina nezmäkne.",
          "Nechaj baklažány vychladnúť, prekroj ich a vyber dužinu lyžicou; kožu zahoď.",
          "Nechaj dužinu odkvapkať v site aspoň desať minút — prebytočná voda by nátierku rozriedila.",
          "Roztlač cesnak so soľou na pastu a zmiešaj ju s tahini, citrónovou šťavou a rímskou rascou.",
          "Vmiešaj dužinu a rozotri všetko vidličkou; nátierka má zostať hrubá, nie hladká ako pyré.",
          "Pokvapkaj olivovým olejom a posyp nasekaným petržlenom."],
  tipy:"Nátierku miešaj vidličkou, nie mixérom — rozmixovaná stratí štruktúru a chutí ako maz.",
  tagy:["nátierka","bezmäsité","baklažán","blízkovýchodná kuchyňa","zelenina"] },

// ── KURACIE ───────────────────────────────────────────────────────────────────
{ id:"kuracie-s-kuskusom", nazov:"Kuracie s kuskusom po marocky", en:"Chicken Couscous", mealId:"52850",
  kat:"Hlavné jedlo", kuchyna:"Marocká", cas:"40 min", porcie:4, hlavna:"Kuracie prsia", narocnost:"jednoduchá",
  popis:"Marocký tanier: kuracie so zeleninou a cícerom nad kuskusom, dochutené harissou a sušenými marhuľami.",
  ing:[i("Kuracie prsia",500,"g","na kocky"),i("Kuskus",300,"g"),i("Cuketa",200,"g"),
       i("Mrkva",150,"g"),i("Cícer",240,"g","scedený"),i("Olivový olej",2,"PL"),
       i("Harissa",1,"ČL"),i("Kurací vývar",400,"ml"),i("Sušené marhule",60,"g"),i("Karí korenie",1,"ČL")],
  postup:["Nakrájaj kuracie prsia na kocky, osoľ ich a opeč na olivovom oleji dozlatista.",
          "Pridaj mrkvu a cuketu na kolieska a restuj päť minút.",
          "Vmiešaj harissu a karí korenie a nechaj ich minútu rozvoňať.",
          "Prilej polovicu vývaru, pridaj cícer a nasekané sušené marhule a dus desať minút.",
          "Zalej kuskus zvyškom horúceho vývaru, prikry a nechaj päť minút napučať; potom ho prevzdušni vidličkou.",
          "Navŕš dusené kuracie so zeleninou na kuskus a podávaj."],
  tipy:"Kuskus sa nevarí, len zaparí — pomer je jeden diel kuskusu na jeden diel vriaceho vývaru.",
  tagy:["kuracie","kuskus","marocká kuchyňa","zelenina","rýchle"] }

];
