// Vlna 5 — 36 receptov s vysokým obsahom vlákniny (strukoviny, celozrnné, koreňová zelenina).
// Cieľ: zdvihnúť priemer vlákniny z 18,5 g/deň na 25–30 g bez zásahu do generátora.
// Kategórie sú volené tak, aby ich generátor SKUTOČNE vedel vybrať: Hlavné jedlo, Cestoviny,
// Polievka a Šalát sú v `SLOT_KATEGORIE` pre Obed a Večeru. Kategória Príloha v `SLOT_KATEGORIE`
// nie je — tie recepty sú na ručné pridanie do plánu (generátor prikladá vlastné `prf:*` tokeny).
"use strict";
const i = (nazov, mnozstvo, jednotka, poznamka) => ({ nazov, mnozstvo, jednotka, poznamka: poznamka || "" });

module.exports = [

// ── HLAVNÉ JEDLÁ ───────────────────────────────────────────────────────────────
{ id:"sosovicovy-gulas-s-korenovou-zeleninou", nazov:"Šošovicový guláš s koreňovou zeleninou", kat:"Hlavné jedlo", kuchyna:"Slovenská", cas:"45 min", porcie:4, hlavna:"Šošovica", narocnost:"stredná",
  popis:"Hustý guláš zo šošovice, mrkvy a zeleru so zemiakmi — 14 g vlákniny na porciu.",
  ing:[i("Šošovica",340,"g"),i("Mrkva",320,"g"),i("Zeler",160,"g"),i("Cibuľa",240,"g"),i("Zemiaky",400,"g"),i("Paradajkový pretlak",160,"g"),i("Olivový olej",32,"g"),i("Rasca",4,"g")],
  postup:["Prepláchni šošovicu v cedníku pod studenou vodou.","Nakrájaj cibuľu, mrkvu, zeler a zemiaky na kocky a orestuj cibuľu na oleji dosklovita.","Pridaj zeleninu, šošovicu, pretlak a rascu, zalej vodou a var 35 minút domäkka. Nakoniec osoľ."],
  tipy:"Šošovicu soľ až na konci — v slanej vode tvrdne a varí sa dvakrát tak dlho.",
  tagy:["hlavné jedlo","strukoviny","vláknina","bezmäsité","slovenská"] },

{ id:"cicerovy-gulas-s-paprikou", nazov:"Cícerový guláš s paprikou", kat:"Hlavné jedlo", kuchyna:"Maďarská", cas:"30 min", porcie:4, hlavna:"Cícer",
  popis:"Cícer dusený s paprikou a paradajkovým pretlakom — hotový za pol hodiny.",
  ing:[i("Cícer",800,"g"),i("Paprika červená",400,"g"),i("Cibuľa",240,"g"),i("Paradajkový pretlak",200,"g"),i("Olivový olej",32,"g"),i("Cesnak",12,"g")],
  postup:["Sceď cícer z konzervy a prepláchni ho pod studenou vodou.","Orestuj nakrájanú cibuľu s cesnakom na oleji a pridaj nakrájanú papriku.","Vmiešaj pretlak a cícer, zalej vodou a dus 15 minút. Osoľ a okoreň."],
  tipy:"Guláš je hustejší, keď časť cíceru roztlačíš vidličkou priamo v hrnci.",
  tagy:["hlavné jedlo","strukoviny","vláknina","bezmäsité"] },

{ id:"fazulovy-gulas-s-klobasou", nazov:"Fazuľový guláš s klobásou", kat:"Hlavné jedlo", kuchyna:"Slovenská", cas:"40 min", porcie:4, hlavna:"Fazuľa",
  popis:"Sýty fazuľový guláš s údenou klobásou, paprikou a zemiakmi.",
  ing:[i("Fazuľa červená",800,"g"),i("Klobása",160,"g"),i("Cibuľa",240,"g"),i("Paprika červená",320,"g"),i("Zemiaky",400,"g"),i("Paradajkový pretlak",160,"g"),i("Rasca",4,"g")],
  postup:["Nakrájaj klobásu na kolieska a vyškvar ju na suchej panvici.","Pridaj nasekanú cibuľu, papriku a zemiaky nakrájané na kocky a krátko orestuj.","Vmiešaj scedenú fazuľu, pretlak a rascu, zalej vodou a var 25 minút."],
  tipy:"Klobása je slaná — osoľ až celkom na konci.",
  tagy:["hlavné jedlo","strukoviny","vláknina","slovenská"] },

{ id:"bulgurove-rizoto-so-zeleninou", nazov:"Bulgurové rizoto so zeleninou", kat:"Hlavné jedlo", kuchyna:"Blízkovýchodná", cas:"30 min", porcie:4, hlavna:"Bulgur",
  popis:"Bulgur dusený s cuketou, paprikou a mrkvou — celozrnná náhrada rizota.",
  ing:[i("Bulgur",340,"g"),i("Cuketa",480,"g"),i("Paprika červená",320,"g"),i("Mrkva",240,"g"),i("Cibuľa",200,"g"),i("Olivový olej",40,"g")],
  postup:["Nakrájaj cuketu, papriku, mrkvu a cibuľu na kocky.","Orestuj zeleninu na oleji päť minút, kým nezmäkne.","Vsyp bulgur, zalej dvojnásobkom vody, prikry a dus 15 minút domäkka."],
  tipy:"Bulgur nasiakne presne dvojnásobok svojho objemu vody — nemieš ho počas dusenia.",
  tagy:["hlavné jedlo","celozrnné","vláknina","bezmäsité"] },

{ id:"pohankova-kasa-s-hubami-a-cibulkou", nazov:"Pohánková kaša s hubami a cibuľkou", kat:"Hlavné jedlo", kuchyna:"Slovenská", cas:"30 min", porcie:4, hlavna:"Pohánka",
  popis:"Pohánka so šampiňónmi a cibuľkou, zjemnená lyžicou smotany.",
  ing:[i("Pohánka",340,"g"),i("Šampiňóny",600,"g"),i("Cibuľa",240,"g"),i("Olivový olej",40,"g"),i("Smotana na varenie",120,"g"),i("Petržlenová vňať",20,"g")],
  postup:["Prepláchni pohánku a zalej ju dvojnásobkom vody, prikry a var 15 minút.","Nakrájaj šampiňóny na plátky a cibuľu nadrobno a orestuj ich na oleji dozlatista.","Vmiešaj huby do uvarenej pohánky, prilej smotanu, osoľ a posyp nasekanou vňaťou."],
  tipy:"Pohánku pred varením opraž nasucho — chuť bude orieškovejšia.",
  tagy:["hlavné jedlo","celozrnné","vláknina","bezmäsité"] },

{ id:"quinoa-s-pecenou-zeleninou-a-fetou", nazov:"Quinoa s pečenou zeleninou a fetou", kat:"Hlavné jedlo", kuchyna:"Stredomorská", cas:"40 min", porcie:4, hlavna:"Quinoa", narocnost:"stredná",
  popis:"Quinoa s brokolicou, paprikou a fetou pečenou v rúre.",
  ing:[i("Quinoa",280,"g"),i("Brokolica",480,"g"),i("Paprika červená",400,"g"),i("Feta",160,"g"),i("Olivový olej",40,"g"),i("Cibuľa červená",200,"g")],
  postup:["Predhrej rúru na 200 °C.","Nakrájaj brokolicu, papriku a cibuľu, pokvapkaj olejom, osoľ a peč 25 minút.","Prepláchni quinou, uvar ju 15 minút v dvojnásobku vody a zmiešaj s pečenou zeleninou a rozdrobenou fetou."],
  tipy:"Quinou pred varením vždy prepláchni — inak je horkastá.",
  tagy:["hlavné jedlo","celozrnné","vláknina","bezmäsité"] },

{ id:"celozrnne-cestoviny-s-brokolicou-a-cicerom", nazov:"Celozrnné cestoviny s brokolicou a cícerom", kat:"Cestoviny", kuchyna:"Talianska", cas:"25 min", porcie:4, hlavna:"Celozrnné cestoviny",
  popis:"Celozrnné cestoviny s brokolicou, cícerom a cesnakom — 18 g vlákniny na porciu.",
  ing:[i("Celozrnné cestoviny",280,"g"),i("Brokolica",600,"g"),i("Cícer",480,"g"),i("Olivový olej",40,"g"),i("Cesnak",20,"g"),i("Petržlenová vňať",20,"g")],
  postup:["Uvar celozrnné cestoviny v osolenej vode podľa návodu na obale.","Rozober brokolicu na ružičky a povar ju posledných päť minút spolu s cestovinami.","Orestuj plátky cesnaku na oleji, pridaj scedený cícer, vmiešaj cestoviny s brokolicou a posyp vňaťou."],
  tipy:"Odlož si šálku vody z cestovín — rozriedi omáčku lepšie než čerstvá voda.",
  tagy:["cestoviny","strukoviny","vláknina","bezmäsité"] },

{ id:"celozrnne-cestoviny-so-sosovicovym-ragu", nazov:"Celozrnné cestoviny so šošovicovým ragú", kat:"Cestoviny", kuchyna:"Talianska", cas:"40 min", porcie:4, hlavna:"Šošovica", narocnost:"stredná",
  popis:"Bezmäsité boloňské ragú zo šošovice na celozrnných cestovinách.",
  ing:[i("Celozrnné cestoviny",280,"g"),i("Šošovica",180,"g"),i("Paradajkový pretlak",240,"g"),i("Mrkva",240,"g"),i("Cibuľa",200,"g"),i("Olivový olej",32,"g"),i("Oregano",4,"g")],
  postup:["Nakrájaj mrkvu a cibuľu nadrobno a orestuj ich na oleji.","Pridaj prepláchnutú šošovicu, pretlak a oregano, zalej vodou a var 30 minút domäkka.","Uvar cestoviny, sceď ich a zmiešaj s ragú. Osoľ a okoreň."],
  tipy:"Ragú je na druhý deň lepšie — pokojne ho uvar večer dopredu.",
  tagy:["cestoviny","strukoviny","vláknina","bezmäsité"] },

{ id:"krupy-s-kelom-a-zemiakmi", nazov:"Krúpy s kelom a zemiakmi", kat:"Hlavné jedlo", kuchyna:"Slovenská", cas:"45 min", porcie:4, hlavna:"Krúpy", narocnost:"stredná",
  popis:"Stará slovenská kombinácia — jačmenné krúpy, kel a zemiaky v jednom hrnci.",
  ing:[i("Krúpy",280,"g"),i("Kel",720,"g"),i("Zemiaky",480,"g"),i("Cibuľa",200,"g"),i("Olivový olej",32,"g"),i("Majoránka",4,"g")],
  postup:["Prepláchni krúpy a zalej ich trojnásobkom vody, var 25 minút.","Nakrájaj kel na pásiky a zemiaky na kocky a orestuj cibuľu na oleji.","Pridaj kel so zemiakmi ku krúpam, dovar 15 minút, osoľ a dochuť majoránkou."],
  tipy:"Krúpy majú 15 g vlákniny na 100 g — z bežných príloh najviac.",
  tagy:["hlavné jedlo","celozrnné","vláknina","slovenská"] },

{ id:"sosovicove-karbonatky-s-ovsenymi-vlockami", nazov:"Šošovicové karbonátky s ovsenými vločkami", kat:"Hlavné jedlo", kuchyna:"Slovenská", cas:"40 min", porcie:4, hlavna:"Šošovica", narocnost:"stredná",
  popis:"Bezmäsité karbonátky zo šošovice, mrkvy a ovsených vločiek.",
  ing:[i("Šošovica",240,"g"),i("Ovsené vločky",100,"g"),i("Vajcia",2,"ks"),i("Mrkva",240,"g"),i("Cibuľa",160,"g"),i("Olivový olej",24,"g"),i("Cesnak",12,"g")],
  postup:["Uvar prepláchnutú šošovicu domäkka, sceď ju a nechaj vychladnúť.","Roztlač šošovicu vidličkou, primiešaj nastrúhanú mrkvu, nasekanú cibuľu, cesnak, vločky a vajcia. Osoľ.","Vytvaruj karbonátky a opeč ich na oleji z oboch strán dozlatista."],
  tipy:"Zmes nechaj pätnásť minút odstáť — vločky nasiaknu vlhkosť a karbonátky držia tvar.",
  tagy:["hlavné jedlo","strukoviny","vláknina","bezmäsité"] },

{ id:"batatove-kari-s-cicerom", nazov:"Batátové kari s cícerom", kat:"Hlavné jedlo", kuchyna:"Indická", cas:"35 min", porcie:4, hlavna:"Batat",
  popis:"Batáty a cícer dusené v kokosovom mlieku s karí korením a špenátom.",
  ing:[i("Batat",720,"g"),i("Cícer",600,"g"),i("Kokosové mlieko",240,"g"),i("Cibuľa",200,"g"),i("Karí korenie",20,"g"),i("Špenát",240,"g"),i("Cesnak",12,"g")],
  postup:["Nakrájaj batáty na kocky a cibuľu nadrobno.","Orestuj cibuľu s cesnakom a karí korením, pridaj batáty a zalej kokosovým mliekom s vodou.","Dus 20 minút, potom vmiešaj scedený cícer a špenát a nechaj prejsť varom."],
  tipy:"Karí korenie vždy krátko opraž na tuku — inak zostane múčnaté.",
  tagy:["hlavné jedlo","strukoviny","vláknina","bezmäsité"] },

{ id:"zapekana-brokolica-so-sosovicou-a-syrom", nazov:"Zapekaná brokolica so šošovicou a syrom", kat:"Hlavné jedlo", kuchyna:"Slovenská", cas:"45 min", porcie:4, hlavna:"Brokolica", narocnost:"stredná",
  popis:"Brokolica a šošovica zapečené s vajcovo-mliečnym zálievkou a syrom.",
  ing:[i("Šošovica",220,"g"),i("Brokolica",800,"g"),i("Syr eidam",140,"g"),i("Mlieko",320,"ml"),i("Vajcia",2,"ks"),i("Cesnak",10,"g")],
  postup:["Uvar prepláchnutú šošovicu domäkka a sceď ju.","Rozober brokolicu na ružičky, blanšíruj ju tri minúty a vylož do zapekacej misy spolu so šošovicou.","Rozšľahaj vajcia s mliekom a cesnakom, zalej tým misu, posyp syrom a zapekaj 25 minút pri 190 °C."],
  tipy:"Brokolicu blanšíruj len krátko — v rúre sa dopečie a nerozvarí sa na kašu.",
  tagy:["hlavné jedlo","strukoviny","vláknina","zapekané"] },

{ id:"chilli-sin-carne-s-fazulou-a-kukuricou", nazov:"Chilli sin carne s fazuľou a kukuricou", kat:"Hlavné jedlo", kuchyna:"Mexická", cas:"35 min", porcie:4, hlavna:"Fazuľa",
  popis:"Bezmäsité chilli z červenej fazule, kukurice a papriky.",
  ing:[i("Fazuľa červená",800,"g"),i("Kukurica sladká",320,"g"),i("Paradajkový pretlak",240,"g"),i("Paprika červená",320,"g"),i("Cibuľa",240,"g"),i("Olivový olej",32,"g"),i("Chilli",20,"g")],
  postup:["Nakrájaj cibuľu a papriku na kocky a orestuj ich na oleji.","Pridaj pretlak a nasekané chilli a krátko prehrej.","Vmiešaj scedenú fazuľu s kukuricou, zalej vodou a dus 20 minút. Osoľ."],
  tipy:"Štipku škorice do chilli nikto nespozná, ale chuť sa zaokrúhli.",
  tagy:["hlavné jedlo","strukoviny","vláknina","bezmäsité"] },

{ id:"pecena-tekvica-s-quinoou-a-cicerom", nazov:"Pečená tekvica s quinoou a cícerom", kat:"Hlavné jedlo", kuchyna:"Stredomorská", cas:"45 min", porcie:4, hlavna:"Tekvica", narocnost:"stredná",
  popis:"Pečená tekvica hokkaido s quinoou, cícerom a červenou cibuľou.",
  ing:[i("Quinoa",220,"g"),i("Cícer",560,"g"),i("Tekvica",720,"g"),i("Olivový olej",40,"g"),i("Cibuľa červená",160,"g"),i("Tymian",4,"g")],
  postup:["Predhrej rúru na 200 °C a nakrájaj tekvicu na kocky.","Zmiešaj tekvicu so scedeným cícerom a cibuľou, pokvapkaj olejom, posyp tymianom a peč 30 minút.","Uvar prepláchnutú quinou v dvojnásobku vody a zmiešaj ju s pečenou zeleninou."],
  tipy:"Hokkaido sa nešúpe — šupka po pečení zmäkne a nesie vlákninu.",
  tagy:["hlavné jedlo","celozrnné","vláknina","bezmäsité"] },

{ id:"mexicka-panvica-s-fazulou-a-bulgurom", nazov:"Mexická panvica s fazuľou a bulgurom", kat:"Hlavné jedlo", kuchyna:"Mexická", cas:"30 min", porcie:4, hlavna:"Bulgur",
  popis:"Jednopanvicové jedlo z bulguru, fazule, kukurice a papriky.",
  ing:[i("Bulgur",240,"g"),i("Fazuľa červená",600,"g"),i("Paprika červená",320,"g"),i("Kukurica sladká",240,"g"),i("Paradajkový pretlak",160,"g"),i("Olivový olej",32,"g"),i("Chilli",12,"g")],
  postup:["Orestuj nakrájanú papriku na oleji a pridaj nasekané chilli.","Vsyp bulgur, vmiešaj pretlak a zalej dvojnásobkom vody.","Dus 15 minút, potom vmiešaj scedenú fazuľu s kukuricou a nechaj prehriať."],
  tipy:"Panvicu podávaj s lyžicou kyslej smotany — zmierni pálivosť.",
  tagy:["hlavné jedlo","strukoviny","vláknina","bezmäsité"] },

// ── POLIEVKY ───────────────────────────────────────────────────────────────────
{ id:"sosovicova-polievka-s-mrkvou-a-zemiakmi", nazov:"Šošovicová polievka s mrkvou a zemiakmi", kat:"Polievka", kuchyna:"Slovenská", cas:"40 min", porcie:4, hlavna:"Šošovica",
  popis:"Hustá šošovicová polievka so zeleninou — klasika, ktorá zasýti aj ako hlavné jedlo.",
  ing:[i("Šošovica",220,"g"),i("Mrkva",320,"g"),i("Zemiaky",480,"g"),i("Cibuľa",160,"g"),i("Olivový olej",20,"g"),i("Zeleninový vývar",1600,"ml"),i("Majoránka",3,"g")],
  postup:["Prepláchni šošovicu a nakrájaj zeleninu na kocky.","Orestuj cibuľu na oleji, pridaj mrkvu a zemiaky a krátko prehrej.","Zalej vývarom, vsyp šošovicu a var 30 minút. Dochuť majoránkou a osoľ."],
  tipy:"Lyžica octu na konci polievku rozjasní — pridaj ju mimo platne.",
  tagy:["polievka","strukoviny","vláknina","slovenská"] },

{ id:"fazulova-polievka-s-kyslou-kapustou", nazov:"Fazuľová polievka s kyslou kapustou", kat:"Polievka", kuchyna:"Slovenská", cas:"35 min", porcie:4, hlavna:"Fazuľa",
  popis:"Kyslá fazuľová polievka s kapustou a zemiakmi — 17 g vlákniny na porciu.",
  ing:[i("Fazuľa biela",720,"g"),i("Kyslá kapusta",480,"g"),i("Zemiaky",400,"g"),i("Cibuľa",160,"g"),i("Olivový olej",24,"g"),i("Zeleninový vývar",1400,"ml"),i("Rasca",3,"g")],
  postup:["Orestuj nasekanú cibuľu na oleji a pridaj rascu.","Vlož nakrájané zemiaky a kyslú kapustu, zalej vývarom a var 20 minút.","Vmiešaj scedenú fazuľu, nechaj prejsť varom a osoľ."],
  tipy:"Ak je kapusta veľmi kyslá, prepláchni ju studenou vodou.",
  tagy:["polievka","strukoviny","vláknina","slovenská"] },

{ id:"cicerova-polievka-s-paradajkami-a-rozmarinom", nazov:"Cícerová polievka s paradajkami a rozmarínom", kat:"Polievka", kuchyna:"Talianska", cas:"30 min", porcie:4, hlavna:"Cícer",
  popis:"Stredomorská polievka z cíceru a paradajok voňajúca rozmarínom.",
  ing:[i("Cícer",720,"g"),i("Paradajky",600,"g"),i("Cibuľa",200,"g"),i("Olivový olej",32,"g"),i("Zeleninový vývar",1400,"ml"),i("Rozmarín",8,"g"),i("Cesnak",12,"g")],
  postup:["Orestuj nasekanú cibuľu s cesnakom a rozmarínom na oleji.","Pridaj nakrájané paradajky a nechaj ich rozpadnúť.","Vsyp scedený cícer, zalej vývarom a var 15 minút. Časť polievky rozmixuj a vráť späť."],
  tipy:"Rozmixovaná tretina polievky ju zahustí bez zápražky aj bez smotany.",
  tagy:["polievka","strukoviny","vláknina","bezmäsité"] },

{ id:"hrachova-polievka-so-zeleninou", nazov:"Hrachová polievka so zeleninou", kat:"Polievka", kuchyna:"Slovenská", cas:"40 min", porcie:4, hlavna:"Hrach",
  popis:"Hustá hrachová polievka s mrkvou a zemiakmi, dochutená majoránkou.",
  ing:[i("Hrach žltý",800,"g"),i("Mrkva",240,"g"),i("Zemiaky",400,"g"),i("Cibuľa",160,"g"),i("Olivový olej",24,"g"),i("Zeleninový vývar",1400,"ml"),i("Majoránka",4,"g")],
  postup:["Orestuj nasekanú cibuľu na oleji dosklovita.","Pridaj hrach, nakrájanú mrkvu a zemiaky a zalej vývarom.","Var 30 minút domäkka, dochuť majoránkou a osoľ."],
  tipy:"Hrachovú polievku podávaj s opečenými kockami celozrnného chleba.",
  tagy:["polievka","strukoviny","vláknina","slovenská"] },

{ id:"brokolicovy-krem-so-slnecnicovymi-semienkami", nazov:"Brokolicový krém so slnečnicovými semienkami", kat:"Polievka", kuchyna:"Slovenská", cas:"30 min", porcie:4, hlavna:"Brokolica",
  popis:"Zamatový brokolicový krém posypaný praženými slnečnicovými semienkami.",
  ing:[i("Brokolica",1200,"g"),i("Zemiaky",480,"g"),i("Slnečnicové semienka",60,"g"),i("Mlieko",320,"ml"),i("Cibuľa",160,"g"),i("Olivový olej",20,"g"),i("Zeleninový vývar",1000,"ml")],
  postup:["Orestuj nasekanú cibuľu na oleji a pridaj nakrájané zemiaky.","Zalej vývarom, pridaj ružičky brokolice a var 15 minút.","Rozmixuj polievku dohladka, prilej mlieko a posyp praženými semienkami."],
  tipy:"Pár ružičiek brokolice si odlož neroztlačených — krém bude vyzerať lepšie.",
  tagy:["polievka","zelenina","vláknina","bezmäsité"] },

{ id:"kelova-polievka-s-krupami", nazov:"Kelová polievka s krúpami", kat:"Polievka", kuchyna:"Slovenská", cas:"45 min", porcie:4, hlavna:"Kel", narocnost:"stredná",
  popis:"Zimná polievka z kelu a jačmenných krúp — 17 g vlákniny na porciu.",
  ing:[i("Kel",1000,"g"),i("Krúpy",160,"g"),i("Mrkva",240,"g"),i("Cibuľa",160,"g"),i("Olivový olej",24,"g"),i("Zeleninový vývar",1400,"ml"),i("Majoránka",3,"g")],
  postup:["Prepláchni krúpy a zalej ich vývarom, var 20 minút.","Nakrájaj kel na pásiky a mrkvu na kolieska, cibuľu orestuj na oleji.","Pridaj zeleninu ku krúpam, dovar 15 minút a dochuť majoránkou a soľou."],
  tipy:"Krúpy polievku počas státia ďalej zahusťujú — na druhý deň ju rozrieď vodou.",
  tagy:["polievka","celozrnné","vláknina","slovenská"] },

{ id:"mrkvovo-sosovicovy-krem-s-kokosovym-mliekom", nazov:"Mrkvovo-šošovicový krém s kokosovým mliekom", kat:"Polievka", kuchyna:"Indická", cas:"35 min", porcie:4, hlavna:"Mrkva",
  popis:"Krém z mrkvy a červenej šošovice s kokosovým mliekom a zázvorom.",
  ing:[i("Mrkva",1000,"g"),i("Šošovica červená",200,"g"),i("Kokosové mlieko",240,"g"),i("Cibuľa",160,"g"),i("Zázvor",20,"g"),i("Zeleninový vývar",1200,"ml"),i("Karí korenie",8,"g")],
  postup:["Orestuj nasekanú cibuľu so strúhaným zázvorom a karí korením.","Pridaj nakrájanú mrkvu a prepláchnutú červenú šošovicu a zalej vývarom.","Var 25 minút, rozmixuj dohladka a vmiešaj kokosové mlieko."],
  tipy:"Červená šošovica sa rozvarí sama — krém netreba zahusťovať múkou.",
  tagy:["polievka","strukoviny","vláknina","bezmäsité"] },

{ id:"polievka-z-cervenej-sosovice-s-kelom", nazov:"Polievka z červenej šošovice s kelom", kat:"Polievka", kuchyna:"Slovenská", cas:"35 min", porcie:4, hlavna:"Šošovica červená",
  popis:"Červená šošovica s kelom, mrkvou a zemiakmi v jednom hrnci.",
  ing:[i("Šošovica červená",220,"g"),i("Kel",600,"g"),i("Mrkva",240,"g"),i("Zemiaky",320,"g"),i("Cibuľa",160,"g"),i("Olivový olej",24,"g"),i("Zeleninový vývar",1400,"ml")],
  postup:["Orestuj nasekanú cibuľu na oleji.","Pridaj nakrájanú mrkvu, zemiaky a prepláchnutú šošovicu a zalej vývarom.","Var 20 minút, pridaj kel nakrájaný na pásiky a dovar päť minút. Osoľ."],
  tipy:"Kel dávaj až nakoniec — dlhým varom stratí farbu aj chuť.",
  tagy:["polievka","strukoviny","vláknina","slovenská"] },

{ id:"tekvicovy-krem-s-tekvicovymi-semienkami", nazov:"Tekvicový krém s tekvicovými semienkami", kat:"Polievka", kuchyna:"Slovenská", cas:"35 min", porcie:4, hlavna:"Tekvica",
  popis:"Krém z hokkaido tekvice s kokosovým mliekom a praženými semienkami.",
  ing:[i("Tekvica",1400,"g"),i("Zemiaky",400,"g"),i("Tekvicové semienka",60,"g"),i("Kokosové mlieko",200,"g"),i("Cibuľa",160,"g"),i("Zeleninový vývar",1200,"ml"),i("Zázvor",12,"g")],
  postup:["Nakrájaj tekvicu a zemiaky na kocky a cibuľu nadrobno.","Orestuj cibuľu so strúhaným zázvorom, pridaj zeleninu a zalej vývarom.","Var 25 minút, rozmixuj dohladka, vmiešaj kokosové mlieko a posyp praženými semienkami."],
  tipy:"Hokkaido sa nešúpe — ušetríš prácu a šupka sa rozmixuje bez zvyšku.",
  tagy:["polievka","zelenina","vláknina","bezmäsité"] },

// ── ŠALÁTY ─────────────────────────────────────────────────────────────────────
{ id:"cicerovy-salat-s-uhorkou-a-fetou", nazov:"Cícerový šalát s uhorkou a fetou", kat:"Šalát", kuchyna:"Grécka", cas:"15 min", porcie:2, hlavna:"Cícer",
  popis:"Grécky ladený šalát z cíceru, uhorky, paradajok a fety.",
  ing:[i("Cícer",320,"g"),i("Uhorka",240,"g"),i("Paradajky",200,"g"),i("Feta",60,"g"),i("Olivový olej",16,"g"),i("Cibuľa červená",60,"g"),i("Oregano",2,"g")],
  postup:["Sceď cícer a prepláchni ho pod studenou vodou.","Nakrájaj uhorku, paradajky a cibuľu na kocky.","Zmiešaj všetko s olejom a oreganom, osoľ a posyp rozdrobenou fetou."],
  tipy:"Šalát nechaj pred podávaním pol hodiny odstáť — cícer nasiakne dresing.",
  tagy:["šalát","strukoviny","vláknina","bezmäsité"] },

{ id:"sosovicovy-salat-s-cviklou-a-orechmi", nazov:"Šošovicový šalát s cviklou a vlašskými orechmi", kat:"Šalát", kuchyna:"Slovenská", cas:"30 min", porcie:2, hlavna:"Šošovica",
  popis:"Vlažný šalát z uvarenej šošovice, pečenej cvikly a orechov.",
  ing:[i("Šošovica",120,"g"),i("Cvikla",300,"g"),i("Vlašské orechy",30,"g"),i("Rukola",60,"g"),i("Olivový olej",16,"g"),i("Citrónová šťava",20,"g")],
  postup:["Uvar prepláchnutú šošovicu 20 minút domäkka a sceď ju.","Nakrájaj uvarenú cviklu na kocky a nasekaj orechy nahrubo.","Zmiešaj šošovicu s cviklou, pokvapkaj olejom a citrónom, osoľ a doplň rukolu s orechmi."],
  tipy:"Cviklu uvar v šupke — nepustí farbu a lepšie sa šúpe.",
  tagy:["šalát","strukoviny","vláknina","bezmäsité"] },

{ id:"bulgurovy-salat-tabbouleh", nazov:"Bulgurový šalát tabbouleh", kat:"Šalát", kuchyna:"Blízkovýchodná", cas:"20 min", porcie:2, hlavna:"Bulgur",
  popis:"Libanonský šalát z bulguru, paradajok a veľkého množstva petržlenovej vňate.",
  ing:[i("Bulgur",120,"g"),i("Paradajky",300,"g"),i("Petržlenová vňať",60,"g"),i("Uhorka",200,"g"),i("Olivový olej",20,"g"),i("Citrónová šťava",30,"g"),i("Jarná cibuľka",40,"g")],
  postup:["Zalej bulgur horúcou vodou v pomere jedna k jednej a nechaj ho 15 minút napučať.","Nakrájaj paradajky a uhorku na drobné kocky a nasekaj vňať s cibuľkou.","Zmiešaj všetko s olejom a citrónovou šťavou a osoľ."],
  tipy:"Vňate má byť veľa — tabbouleh je bylinkový šalát s bulgurom, nie naopak.",
  tagy:["šalát","celozrnné","vláknina","bezmäsité"] },

{ id:"fazulovy-salat-s-kukuricou-a-paprikou", nazov:"Fazuľový šalát s kukuricou a paprikou", kat:"Šalát", kuchyna:"Mexická", cas:"15 min", porcie:2, hlavna:"Fazuľa",
  popis:"Rýchly šalát z červenej fazule, kukurice a papriky s limetkovým dresingom.",
  ing:[i("Fazuľa červená",400,"g"),i("Kukurica sladká",160,"g"),i("Paprika červená",200,"g"),i("Cibuľa červená",80,"g"),i("Olivový olej",20,"g"),i("Citrónová šťava",20,"g"),i("Petržlenová vňať",20,"g")],
  postup:["Sceď fazuľu aj kukuricu a prepláchni ich pod studenou vodou.","Nakrájaj papriku a cibuľu na kocky.","Zmiešaj všetko s olejom a citrónovou šťavou, osoľ a posyp nasekanou vňaťou."],
  tipy:"Šalát vydrží v chladničke tri dni — hodí sa do obedára.",
  tagy:["šalát","strukoviny","vláknina","bezmäsité"] },

{ id:"quinoa-salat-so-spenatom-a-cicerom", nazov:"Quinoa šalát so špenátom a cícerom", kat:"Šalát", kuchyna:"Stredomorská", cas:"25 min", porcie:2, hlavna:"Quinoa",
  popis:"Quinoa s cícerom, čerstvým špenátom a paradajkami.",
  ing:[i("Quinoa",90,"g"),i("Špenát",120,"g"),i("Cícer",200,"g"),i("Paradajky",200,"g"),i("Olivový olej",16,"g"),i("Citrónová šťava",20,"g"),i("Slnečnicové semienka",20,"g")],
  postup:["Prepláchni quinou a uvar ju 15 minút v dvojnásobku vody.","Sceď cícer a nakrájaj paradajky na kocky.","Zmiešaj vychladnutú quinou so špenátom, cícerom a paradajkami, pokvapkaj olejom a citrónom a posyp semienkami."],
  tipy:"Quinou rozotri po tanieri, aby rýchlo vychladla — teplá by špenát zvarila.",
  tagy:["šalát","celozrnné","vláknina","bezmäsité"] },

{ id:"kapustovy-salat-s-mrkvou-a-slnecnicovymi-semienkami", nazov:"Kapustový šalát s mrkvou a slnečnicovými semienkami", kat:"Šalát", kuchyna:"Slovenská", cas:"15 min", porcie:2, hlavna:"Kapusta",
  popis:"Chrumkavý šalát z bielej kapusty, mrkvy a jablka so slnečnicovými semienkami.",
  ing:[i("Kapusta biela",400,"g"),i("Mrkva",200,"g"),i("Slnečnicové semienka",40,"g"),i("Jablko",200,"g"),i("Olivový olej",16,"g"),i("Citrónová šťava",20,"g"),i("Kôpor",8,"g")],
  postup:["Nakrájaj kapustu na tenké pásiky a osoľ ju, nechaj desať minút postáť.","Nastrúhaj mrkvu a jablko nahrubo.","Zmiešaj všetko s olejom, citrónovou šťavou a nasekaným kôprom a posyp semienkami."],
  tipy:"Kapustu po osolení prehnetieš rukou — zmäkne a šalát nebude tvrdý.",
  tagy:["šalát","zelenina","vláknina","bezmäsité"] },

// ── PRÍLOHY (na ručné pridanie do plánu) ──────────────────────────────────────
{ id:"priloha-bulgur-s-petrzlenovou-vnatou", nazov:"Bulgur s petržlenovou vňaťou", kat:"Príloha", kuchyna:"Blízkovýchodná", cas:"20 min", porcie:4, hlavna:"Bulgur",
  popis:"Celozrnná príloha namiesto ryže — bulgur s cibuľkou a petržlenovou vňaťou.",
  ing:[i("Bulgur",280,"g"),i("Cibuľa",120,"g"),i("Olivový olej",20,"g"),i("Petržlenová vňať",60,"g")],
  postup:["Orestuj nasekanú cibuľu na oleji dosklovita.","Vsyp bulgur, zalej dvojnásobkom vody a osoľ.","Prikry a dus 15 minút, potom vmiešaj nasekanú petržlenovú vňať."],
  tipy:"Bulgur má proti bielej ryži takmer desaťnásobok vlákniny.",
  tagy:["príloha","celozrnné","vláknina"] },

{ id:"priloha-pohanka-s-cibulkou", nazov:"Pohánka s cibuľkou", kat:"Príloha", kuchyna:"Slovenská", cas:"20 min", porcie:4, hlavna:"Pohánka",
  popis:"Pohánka opražená a uvarená s cibuľkou — bezlepková príloha.",
  ing:[i("Pohánka",280,"g"),i("Cibuľa",160,"g"),i("Olivový olej",20,"g"),i("Petržlenová vňať",20,"g")],
  postup:["Opraž pohánku nasucho na panvici, kým nezačne voňať.","Orestuj nasekanú cibuľu na oleji a pridaj pohánku.","Zalej dvojnásobkom vody, osoľ, prikry a var 15 minút domäkka."],
  tipy:"Pohánka je bezlepková — hodí sa aj pre celiatikov.",
  tagy:["príloha","celozrnné","vláknina","bezlepkové"] },

{ id:"priloha-quinoa-s-mandlami", nazov:"Quinoa s mandľami", kat:"Príloha", kuchyna:"Stredomorská", cas:"20 min", porcie:4, hlavna:"Quinoa",
  popis:"Quinoa s praženými mandľami a petržlenovou vňaťou.",
  ing:[i("Quinoa",240,"g"),i("Mandle",60,"g"),i("Petržlenová vňať",40,"g"),i("Olivový olej",12,"g")],
  postup:["Prepláchni quinou pod tečúcou vodou.","Uvar ju 15 minút v dvojnásobku osolenej vody.","Opraž nasekané mandle nasucho a vmiešaj ich s vňaťou a olejom do quinoy."],
  tipy:"Quinoa je jediná bežná obilnina s kompletným profilom aminokyselín.",
  tagy:["príloha","celozrnné","vláknina"] },

{ id:"priloha-krupy-so-zeleninou", nazov:"Krúpy so zeleninou", kat:"Príloha", kuchyna:"Slovenská", cas:"35 min", porcie:4, hlavna:"Krúpy",
  popis:"Jačmenné krúpy dusené s mrkvou a zelerom.",
  ing:[i("Krúpy",240,"g"),i("Mrkva",240,"g"),i("Zeler",160,"g"),i("Olivový olej",20,"g"),i("Cibuľa",120,"g")],
  postup:["Prepláchni krúpy pod studenou vodou.","Orestuj nasekanú cibuľu, mrkvu a zeler na oleji.","Vsyp krúpy, zalej trojnásobkom vody, osoľ a var 25 minút domäkka."],
  tipy:"Krúpy pred varením namoč na hodinu — skrátiš varenie na polovicu.",
  tagy:["príloha","celozrnné","vláknina","slovenská"] },

{ id:"priloha-dusena-kapusta-s-jablkom", nazov:"Dusená kapusta s jablkom", kat:"Príloha", kuchyna:"Slovenská", cas:"30 min", porcie:4, hlavna:"Kapusta",
  popis:"Dusená kapusta s jablkom a rascou — klasická príloha k mäsu.",
  ing:[i("Kapusta biela",800,"g"),i("Jablko",320,"g"),i("Cibuľa",160,"g"),i("Olivový olej",20,"g"),i("Rasca",3,"g")],
  postup:["Nakrájaj kapustu na tenké pásiky a jablko na kocky.","Orestuj nasekanú cibuľu na oleji a pridaj rascu.","Vlož kapustu s jablkom, podlej vodou, prikry a dus 20 minút domäkka. Osoľ."],
  tipy:"Lyžica octu na konci kapuste vráti farbu aj chuť.",
  tagy:["príloha","zelenina","vláknina","slovenská"] },

{ id:"priloha-pecena-korenova-zelenina", nazov:"Pečená koreňová zelenina", kat:"Príloha", kuchyna:"Slovenská", cas:"40 min", porcie:4, hlavna:"Mrkva",
  popis:"Mrkva, paštrnák a zeler pečené v rúre s tymianom.",
  ing:[i("Mrkva",600,"g"),i("Paštrnák",480,"g"),i("Zeler",320,"g"),i("Olivový olej",32,"g"),i("Tymian",4,"g")],
  postup:["Predhrej rúru na 200 °C.","Nakrájaj mrkvu, paštrnák a zeler na hrubšie hranolčeky.","Premiešaj zeleninu s olejom, tymianom a soľou a peč 30 minút dozlatista."],
  tipy:"Zeleninu rozlož na plech v jednej vrstve — natesno by sa dusila, nie piekla.",
  tagy:["príloha","zelenina","vláknina","slovenská"] }
];
