// Vlna 5, štvrtá dávka — obedové kcal-pásmo (520–640 kcal na porciu).
// Po tretej dávke sedela hustota vlákniny takto: Raňajky 2,12 · Obed 1,52 · Večera 1,50 · Snack 1,09.
// Obed je najväčší slot (557 kcal medián), takže každá desatina hustoty tam váži najviac.
// Vzorec je rovnaký ako v tretej dávke: strukovina/celozrnná príloha + chudá bielkovina + zelenina,
// aby recept vyhral bielkovinový aj vlákninový člen `skoreJedla` naraz.
"use strict";
const i = (nazov, mnozstvo, jednotka, poznamka) => ({ nazov, mnozstvo, jednotka, poznamka: poznamka || "" });

module.exports = [

{ id:"morcacie-prsia-s-cicerom-a-pecenou-paprikou", nazov:"Morčacie prsia s cícerom a pečenou paprikou", kat:"Hlavné jedlo", kuchyna:"Stredomorská", cas:"35 min", porcie:4, hlavna:"Morčacia šunka",
  popis:"Morčacie mäso s cícerom a pečenou paprikou, dochutené oreganom.",
  ing:[i("Morčacia šunka",480,"g"),i("Cícer",640,"g"),i("Paprika červená",480,"g"),i("Cibuľa",160,"g"),i("Olivový olej",32,"g"),i("Oregano",4,"g"),i("Cesnak",12,"g")],
  postup:["Nakrájaj morčacie mäso na kocky a opeč ho na oleji dozlatista.","Pridaj nakrájanú papriku, cibuľu a cesnak a restuj päť minút.","Vmiešaj scedený cícer s oreganom, podlej vodou a dus 15 minút."],
  tipy:"Morčacie prsia sú chudšie než kuracie — nesuš ich, stačí im desať minút.",
  tagy:["hlavné jedlo","strukoviny","vláknina","mäso","vysoký obsah bielkovín"] },

{ id:"kuracie-prsia-s-krupami-a-hubami", nazov:"Kuracie prsia s krúpami a hubami", kat:"Hlavné jedlo", kuchyna:"Slovenská", cas:"40 min", porcie:4, hlavna:"Krúpy", narocnost:"stredná",
  popis:"Jačmenné krúpy dusené so šampiňónmi a kuracími prsiami.",
  ing:[i("Krúpy",240,"g"),i("Kuracie prsia",440,"g"),i("Šampiňóny",480,"g"),i("Mrkva",240,"g"),i("Cibuľa",160,"g"),i("Olivový olej",28,"g"),i("Petržlenová vňať",20,"g")],
  postup:["Nakrájaj kuracie prsia na kocky a opeč ich na oleji.","Pridaj nakrájané šampiňóny, mrkvu a cibuľu a restuj päť minút.","Vsyp prepláchnuté krúpy, zalej trojnásobkom vody a dus 25 minút. Posyp vňaťou."],
  tipy:"Huby soľ až na konci — soľ z nich vytiahne vodu a nezhnednú.",
  tagy:["hlavné jedlo","celozrnné","vláknina","mäso","vysoký obsah bielkovín"] },

{ id:"hovadzie-so-sosovicou-a-korenovou-zeleninou", nazov:"Hovädzie so šošovicou a koreňovou zeleninou", kat:"Hlavné jedlo", kuchyna:"Slovenská", cas:"45 min", porcie:4, hlavna:"Mleté hovädzie mäso", narocnost:"stredná",
  popis:"Mleté hovädzie mäso dusené so šošovicou, mrkvou a zelerom.",
  ing:[i("Mleté hovädzie mäso",360,"g"),i("Šošovica",240,"g"),i("Mrkva",320,"g"),i("Zeler",200,"g"),i("Cibuľa",160,"g"),i("Paradajkový pretlak",160,"g"),i("Majoránka",4,"g")],
  postup:["Opeč mleté mäso na suchom hrnci dohneda.","Pridaj nasekanú cibuľu, mrkvu a zeler a krátko orestuj.","Vsyp prepláchnutú šošovicu, vmiešaj pretlak, zalej vodou a var 30 minút. Dochuť majoránkou."],
  tipy:"Šošovica s mletým mäsom je najlacnejší spôsob, ako sa dostať k 40 g bielkovín na porciu.",
  tagy:["hlavné jedlo","strukoviny","vláknina","mäso","vysoký obsah bielkovín"] },

{ id:"bravcove-s-fazulou-a-zeleninou", nazov:"Bravčové stehno s fazuľou a zeleninou", kat:"Hlavné jedlo", kuchyna:"Slovenská", cas:"45 min", porcie:4, hlavna:"Bravčové stehno", narocnost:"stredná",
  popis:"Dusené bravčové stehno s bielou fazuľou, mrkvou a paprikou.",
  ing:[i("Bravčové stehno",440,"g"),i("Fazuľa biela",720,"g"),i("Mrkva",320,"g"),i("Paprika červená",320,"g"),i("Cibuľa",160,"g"),i("Paradajkový pretlak",160,"g"),i("Olivový olej",24,"g")],
  postup:["Nakrájaj bravčové stehno na kocky a opeč ho na oleji zo všetkých strán.","Pridaj nasekanú cibuľu, mrkvu a papriku a krátko orestuj.","Vmiešaj pretlak a scedenú fazuľu, zalej vodou a dus 30 minút."],
  tipy:"Bravčové stehno je chudšie než krkovička a v dusenom jedle sa nerozpadne.",
  tagy:["hlavné jedlo","strukoviny","vláknina","mäso","vysoký obsah bielkovín"] },

{ id:"kuracie-prsia-s-quinoou-a-brokolicou", nazov:"Kuracie prsia s quinoou a brokolicou", kat:"Hlavné jedlo", kuchyna:"Stredomorská", cas:"35 min", porcie:4, hlavna:"Quinoa",
  popis:"Quinoa s brokolicou a opečenými kuracími prsiami.",
  ing:[i("Quinoa",220,"g"),i("Kuracie prsia",440,"g"),i("Brokolica",600,"g"),i("Mrkva",240,"g"),i("Olivový olej",28,"g"),i("Cesnak",12,"g")],
  postup:["Prepláchni quinou a uvar ju 15 minút v dvojnásobku osolenej vody.","Nakrájaj kuracie prsia na kocky a opeč ich na oleji s cesnakom.","Pridaj ružičky brokolice a nastrúhanú mrkvu, dus päť minút a zmiešaj s quinoou."],
  tipy:"Brokolicu dus prikrytú — para ju uvarí rýchlejšie než voda a nestratí farbu.",
  tagy:["hlavné jedlo","celozrnné","vláknina","mäso","vysoký obsah bielkovín"] },

{ id:"sosovicove-rizoto-s-kuracim-a-hraskom", nazov:"Šošovicové rizoto s kuracím mäsom a hráškom", kat:"Hlavné jedlo", kuchyna:"Slovenská", cas:"40 min", porcie:4, hlavna:"Šošovica",
  popis:"Šošovica varená s ryžou natural, hráškom a kuracím mäsom.",
  ing:[i("Šošovica",180,"g"),i("Ryža natural",160,"g"),i("Kuracie prsia",400,"g"),i("Zelený hrášok",320,"g"),i("Mrkva",240,"g"),i("Cibuľa",160,"g"),i("Olivový olej",24,"g")],
  postup:["Nakrájaj kuracie prsia na kocky a opeč ich na oleji.","Pridaj nasekanú cibuľu a mrkvu, vsyp prepláchnutú šošovicu a ryžu.","Zalej trojnásobkom vody, var 25 minút a päť minút pred koncom pridaj hrášok."],
  tipy:"Ryža natural a šošovica sa varia rovnako dlho — dajú sa vsypať naraz.",
  tagy:["hlavné jedlo","strukoviny","vláknina","mäso","vysoký obsah bielkovín"] },

{ id:"tuniakove-cestoviny-s-cicerom-a-rukolou", nazov:"Celozrnné cestoviny s tuniakom, cícerom a rukolou", kat:"Cestoviny", kuchyna:"Talianska", cas:"25 min", porcie:4, hlavna:"Tuniak",
  popis:"Celozrnné cestoviny s tuniakom, cícerom, cherry paradajkami a rukolou.",
  ing:[i("Celozrnné cestoviny",240,"g"),i("Tuniak v konzerve",320,"g"),i("Cícer",400,"g"),i("Cherry paradajky",320,"g"),i("Rukola",80,"g"),i("Olivový olej",28,"g"),i("Cesnak",12,"g")],
  postup:["Uvar celozrnné cestoviny v osolenej vode a sceď ich.","Orestuj plátky cesnaku na oleji, pridaj polené paradajky a scedený cícer.","Vmiešaj cestoviny a scedený tuniak, stiahni z platne a zamiešaj rukolu."],
  tipy:"Rukolu vmiešaj mimo platne — teplo jej stačí, aby zvädla akurát.",
  tagy:["cestoviny","strukoviny","vláknina","ryba","vysoký obsah bielkovín"] },

{ id:"kuracie-prsia-s-pohankou-a-kelom", nazov:"Kuracie prsia s pohánkou a kelom", kat:"Hlavné jedlo", kuchyna:"Slovenská", cas:"35 min", porcie:4, hlavna:"Pohánka",
  popis:"Pohánka dusená s kelom a mrkvou, doplnená opečeným kuracím mäsom.",
  ing:[i("Pohánka",200,"g"),i("Kuracie prsia",440,"g"),i("Kel",480,"g"),i("Mrkva",240,"g"),i("Cibuľa",160,"g"),i("Olivový olej",28,"g"),i("Majoránka",4,"g")],
  postup:["Opraž pohánku nasucho a odlož ju bokom.","Nakrájaj kuracie prsia na kocky a opeč ich na oleji, pridaj cibuľu, mrkvu a kel.","Vsyp pohánku, zalej dvojnásobkom vody a dus 15 minút. Dochuť majoránkou."],
  tipy:"Pohánka je bezlepková a varí sa kratšie než ryža natural.",
  tagy:["hlavné jedlo","celozrnné","vláknina","mäso","vysoký obsah bielkovín"] },

{ id:"cicerove-kari-s-kuracim-a-spenatom", nazov:"Cícerové kari s kuracím mäsom a špenátom", kat:"Hlavné jedlo", kuchyna:"Indická", cas:"35 min", porcie:4, hlavna:"Cícer",
  popis:"Cícer a kuracie mäso v kari omáčke so špenátom a paradajkovým pretlakom.",
  ing:[i("Cícer",640,"g"),i("Kuracie prsia",400,"g"),i("Špenát",400,"g"),i("Paradajkový pretlak",200,"g"),i("Kokosové mlieko",160,"g"),i("Karí korenie",16,"g"),i("Cibuľa",160,"g")],
  postup:["Nakrájaj kuracie prsia na kocky a opeč ich na suchom hrnci.","Pridaj nasekanú cibuľu s karí korením a krátko opraž.","Vmiešaj pretlak, scedený cícer a kokosové mlieko, dus 15 minút a nakoniec pridaj špenát."],
  tipy:"Karí je hotové, keď sa olej oddelí od omáčky — vtedy je korenie prepečené.",
  tagy:["hlavné jedlo","strukoviny","vláknina","mäso","vysoký obsah bielkovín"] },

{ id:"zapekany-bulgur-s-morkou-a-zeleninou", nazov:"Zapekaný bulgur s morčacím mäsom a zeleninou", kat:"Hlavné jedlo", kuchyna:"Blízkovýchodná", cas:"45 min", porcie:4, hlavna:"Bulgur", narocnost:"stredná",
  popis:"Bulgur zapečený s morčacím mäsom, paprikou, cuketou a syrom.",
  ing:[i("Bulgur",200,"g"),i("Morčacia šunka",400,"g"),i("Paprika červená",320,"g"),i("Cuketa",320,"g"),i("Syr eidam",120,"g"),i("Paradajkový pretlak",160,"g"),i("Olivový olej",24,"g")],
  postup:["Zalej bulgur dvojnásobkom horúcej vody a nechaj ho 15 minút napučať.","Nakrájaj morčacie mäso a zeleninu na kocky a orestuj ich na oleji s pretlakom.","Zmiešaj bulgur so zmesou, vylož do misy, posyp syrom a zapekaj 20 minút pri 190 °C."],
  tipy:"Bulgur nemusíš variť — stačí ho zaliať horúcou vodou a nechať napučať.",
  tagy:["hlavné jedlo","celozrnné","vláknina","mäso","zapekané"] },

{ id:"fazulovy-kotlik-s-kuracim-a-kukuricou", nazov:"Fazuľový kotlík s kuracím mäsom a kukuricou", kat:"Hlavné jedlo", kuchyna:"Mexická", cas:"35 min", porcie:4, hlavna:"Fazuľa",
  popis:"Červená fazuľa s kuracím mäsom, kukuricou a paprikou.",
  ing:[i("Fazuľa červená",720,"g"),i("Kuracie prsia",400,"g"),i("Kukurica sladká",240,"g"),i("Paprika červená",320,"g"),i("Paradajkový pretlak",200,"g"),i("Cibuľa",160,"g"),i("Chilli",16,"g")],
  postup:["Nakrájaj kuracie prsia na kocky a opeč ich na suchom hrnci dozlatista.","Pridaj nasekanú cibuľu, papriku a chilli a krátko orestuj.","Vmiešaj pretlak, scedenú fazuľu a kukuricu, zalej vodou a dus 15 minút."],
  tipy:"Kotlík zjemníš lyžicou gréckeho jogurtu priamo na tanieri.",
  tagy:["hlavné jedlo","strukoviny","vláknina","mäso","vysoký obsah bielkovín"] },

{ id:"hrachova-kasa-s-kuracim-a-cibulkou", nazov:"Hrachová kaša s kuracím mäsom a cibuľkou", kat:"Hlavné jedlo", kuchyna:"Slovenská", cas:"40 min", porcie:4, hlavna:"Hrach",
  popis:"Hustá hrachová kaša s opečeným kuracím mäsom a restovanou cibuľkou.",
  ing:[i("Hrach žltý",900,"g"),i("Kuracie prsia",400,"g"),i("Cibuľa",240,"g"),i("Mrkva",240,"g"),i("Olivový olej",28,"g"),i("Majoránka",4,"g")],
  postup:["Uvar hrach s nastrúhanou mrkvou domäkka a roztlač ho na hrubú kašu.","Nakrájaj kuracie prsia na kocky a opeč ich na oleji dozlatista.","Orestuj nasekanú cibuľu, zamiešaj ju do kaše a doplň mäso. Dochuť majoránkou."],
  tipy:"Kaša na druhý deň stuhne — rozrieď ju vývarom, nie vodou.",
  tagy:["hlavné jedlo","strukoviny","vláknina","mäso","slovenská"] },

{ id:"sosovicovy-privarok-s-vajcom", nazov:"Šošovicový prívarok s vajcom", kat:"Hlavné jedlo", kuchyna:"Slovenská", cas:"40 min", porcie:4, hlavna:"Šošovica",
  popis:"Klasický šošovicový prívarok s vajcom natvrdo a zemiakmi.",
  ing:[i("Šošovica",280,"g"),i("Vajcia",4,"ks"),i("Zemiaky",560,"g"),i("Cibuľa",160,"g"),i("Mrkva",240,"g"),i("Olivový olej",24,"g"),i("Ocot",15,"g")],
  postup:["Prepláchni šošovicu a uvar ju s nastrúhanou mrkvou domäkka.","Uvar zemiaky na kocky a vajcia natvrdo.","Orestuj nasekanú cibuľu na oleji, zamiešaj ju do prívarku, dochuť octom a doplň polené vajcia."],
  tipy:"Kvapka octu je pre šošovicový prívarok povinná — bez nej chuť zostane plochá.",
  tagy:["hlavné jedlo","strukoviny","vláknina","vajcia","slovenská"] },

{ id:"tofu-s-bulgurom-a-zeleninou", nazov:"Tofu s bulgurom a zeleninou", kat:"Hlavné jedlo", kuchyna:"Ázijská", cas:"30 min", porcie:4, hlavna:"Tofu",
  popis:"Opečené tofu s bulgurom, brokolicou a mrkvou v sójovej omáčke.",
  ing:[i("Tofu",480,"g"),i("Bulgur",200,"g"),i("Brokolica",480,"g"),i("Mrkva",240,"g"),i("Sójová omáčka",40,"g"),i("Olivový olej",28,"g"),i("Sezamové semienka",20,"g")],
  postup:["Nakrájaj tofu na kocky, osuš ho a opeč na oleji dozlatista.","Pridaj nastrúhanú mrkvu a ružičky brokolice a krátko restuj.","Vsyp bulgur, zalej dvojnásobkom vody so sójovou omáčkou a dus 15 minút. Posyp sezamom."],
  tipy:"Tofu opekaj po dávkach — natesno sa dusí a nezhnedne.",
  tagy:["hlavné jedlo","celozrnné","vláknina","bezmäsité","vysoký obsah bielkovín"] },

{ id:"kuracie-prsia-s-cervenou-sosovicou-a-mrkvou", nazov:"Kuracie prsia s červenou šošovicou a mrkvou", kat:"Hlavné jedlo", kuchyna:"Indická", cas:"35 min", porcie:4, hlavna:"Šošovica červená",
  popis:"Červená šošovica varená s mrkvou a kari, doplnená kuracím mäsom.",
  ing:[i("Šošovica červená",240,"g"),i("Kuracie prsia",400,"g"),i("Mrkva",400,"g"),i("Cibuľa",160,"g"),i("Karí korenie",16,"g"),i("Kokosové mlieko",160,"g"),i("Olivový olej",24,"g")],
  postup:["Nakrájaj kuracie prsia na kocky a opeč ich na oleji.","Pridaj nasekanú cibuľu, nastrúhanú mrkvu a karí korenie a krátko opraž.","Vsyp prepláchnutú červenú šošovicu, zalej vodou s kokosovým mliekom a var 20 minút."],
  tipy:"Červená šošovica sa rozvarí na omáčku — netreba nič zahusťovať.",
  tagy:["hlavné jedlo","strukoviny","vláknina","mäso","vysoký obsah bielkovín"] },

{ id:"cottage-zapekane-zemiaky-so-sosovicou", nazov:"Zapekané zemiaky so šošovicou a cottage syrom", kat:"Hlavné jedlo", kuchyna:"Slovenská", cas:"50 min", porcie:4, hlavna:"Zemiaky", narocnost:"stredná",
  popis:"Zemiaky a šošovica zapečené s cottage syrom, vajcami a mrkvou.",
  ing:[i("Zemiaky",800,"g"),i("Šošovica",200,"g"),i("Cottage syr",480,"g"),i("Vajcia",3,"ks"),i("Mrkva",240,"g"),i("Syr eidam",100,"g")],
  postup:["Uvar prepláchnutú šošovicu domäkka a zemiaky v šupke.","Olúp zemiaky, nakrájaj ich na kolieska a vylož do misy so šošovicou a nastrúhanou mrkvou.","Rozšľahaj cottage syr s vajcami, zalej tým misu, posyp eidamom a zapekaj 25 minút pri 190 °C."],
  tipy:"Cottage syr zapekanie nezmastí tak ako smotana a pridá 20 g bielkovín na porciu.",
  tagy:["hlavné jedlo","strukoviny","vláknina","zapekané","vysoký obsah bielkovín"] },

{ id:"kuraci-salat-s-quinoou-a-cicerom", nazov:"Kurací šalát s quinoou a cícerom", kat:"Šalát", kuchyna:"Stredomorská", cas:"30 min", porcie:2, hlavna:"Quinoa",
  popis:"Sýty šalát z quinoy, cíceru, kuracieho mäsa a čerstvej zeleniny.",
  ing:[i("Quinoa",80,"g"),i("Cícer",240,"g"),i("Kuracie prsia",160,"g"),i("Cherry paradajky",200,"g"),i("Uhorka",160,"g"),i("Olivový olej",14,"g"),i("Citrónová šťava",20,"g")],
  postup:["Prepláchni quinou a uvar ju 15 minút, potom ju nechaj vychladnúť.","Nakrájaj kuracie prsia na prúžky a opeč ich na suchej panvici.","Zmiešaj quinou so scedeným cícerom, zeleninou a mäsom a pokvapkaj olejom a citrónom."],
  tipy:"Šalát drží v obedári dva dni — dresing pridaj až pred jedlom.",
  tagy:["šalát","strukoviny","vláknina","mäso","vysoký obsah bielkovín"] },

{ id:"polievka-gulasova-s-fazulou-a-hovadzim", nazov:"Gulášová polievka s fazuľou a hovädzím mäsom", kat:"Polievka", kuchyna:"Maďarská", cas:"45 min", porcie:4, hlavna:"Mleté hovädzie mäso", narocnost:"stredná",
  popis:"Gulášová polievka s hovädzím mäsom, bielou fazuľou a zemiakmi.",
  ing:[i("Mleté hovädzie mäso",320,"g"),i("Fazuľa biela",560,"g"),i("Zemiaky",480,"g"),i("Paprika červená",320,"g"),i("Cibuľa",200,"g"),i("Zeleninový vývar",1400,"ml"),i("Rasca",4,"g")],
  postup:["Opeč mleté mäso na suchom hrnci dohneda.","Pridaj nasekanú cibuľu, papriku, rascu a nakrájané zemiaky a zalej vývarom.","Var 25 minút, vmiešaj scedenú fazuľu a nechaj prejsť varom."],
  tipy:"Fazuľa polievku zahustí sama — zápražku nepotrebuje.",
  tagy:["polievka","strukoviny","vláknina","mäso","vysoký obsah bielkovín"] },

{ id:"minestrone-s-fazulou-a-celozrnnymi-cestovinami", nazov:"Minestrone s fazuľou a celozrnnými cestovinami", kat:"Polievka", kuchyna:"Talianska", cas:"40 min", porcie:4, hlavna:"Fazuľa",
  popis:"Talianska zeleninová polievka s bielou fazuľou a celozrnnými cestovinami.",
  ing:[i("Fazuľa biela",560,"g"),i("Celozrnné cestoviny",120,"g"),i("Mrkva",240,"g"),i("Zeler",160,"g"),i("Cuketa",240,"g"),i("Paradajkový pretlak",160,"g"),i("Zeleninový vývar",1400,"ml"),i("Olivový olej",24,"g")],
  postup:["Nakrájaj mrkvu, zeler a cuketu na kocky a orestuj ich na oleji.","Vmiešaj pretlak, zalej vývarom a var 15 minút.","Vsyp celozrnné cestoviny, dovar podľa obalu a nakoniec pridaj scedenú fazuľu."],
  tipy:"Cestoviny do polievky dávaj až tesne pred podávaním — inak nasiaknu celý vývar.",
  tagy:["polievka","strukoviny","vláknina","bezmäsité"] },

{ id:"kelovy-privarok-s-kuracim-a-zemiakmi", nazov:"Kelový prívarok s kuracím mäsom a zemiakmi", kat:"Hlavné jedlo", kuchyna:"Slovenská", cas:"35 min", porcie:4, hlavna:"Kel",
  popis:"Kelový prívarok zahustený zemiakmi, s opečeným kuracím mäsom.",
  ing:[i("Kel",1000,"g"),i("Zemiaky",640,"g"),i("Kuracie prsia",400,"g"),i("Cibuľa",160,"g"),i("Mlieko",240,"ml"),i("Olivový olej",24,"g"),i("Cesnak",12,"g")],
  postup:["Nakrájaj kel na pásiky a zemiaky na kocky a uvar ich spolu domäkka.","Roztlač časť zemiakov priamo v hrnci a prilej mlieko.","Nakrájaj kuracie prsia na kocky, opeč ich na oleji s cesnakom a vmiešaj do prívarku."],
  tipy:"Kel je zimná zelenina s 3,6 g vlákniny na 100 g — v prívarku ho zjete pol kila.",
  tagy:["hlavné jedlo","zelenina","vláknina","mäso","slovenská"] },

{ id:"ryza-natural-s-kuracim-a-zeleninou", nazov:"Ryža natural s kuracím mäsom a zeleninou", kat:"Hlavné jedlo", kuchyna:"Ázijská", cas:"40 min", porcie:4, hlavna:"Ryža natural",
  popis:"Celozrnná ryža natural restovaná s kuracím mäsom, brokolicou a mrkvou.",
  ing:[i("Ryža natural",220,"g"),i("Kuracie prsia",440,"g"),i("Brokolica",480,"g"),i("Mrkva",240,"g"),i("Sójová omáčka",40,"g"),i("Olivový olej",28,"g"),i("Zázvor",12,"g")],
  postup:["Uvar ryžu natural v dvojnásobku vody 30 minút a nechaj ju odstáť.","Nakrájaj kuracie prsia na prúžky a opeč ich na oleji so strúhaným zázvorom.","Pridaj ružičky brokolice a nastrúhanú mrkvu, krátko restuj a vmiešaj ryžu so sójovou omáčkou."],
  tipy:"Ryža natural má proti bielej takmer trojnásobok vlákniny a varí sa dvakrát dlhšie.",
  tagy:["hlavné jedlo","celozrnné","vláknina","mäso","vysoký obsah bielkovín"] },

{ id:"cicer-s-vajcami-a-pecenou-zeleninou", nazov:"Cícer s vajcami a pečenou zeleninou", kat:"Hlavné jedlo", kuchyna:"Blízkovýchodná", cas:"40 min", porcie:4, hlavna:"Cícer", narocnost:"stredná",
  popis:"Pečený cícer s cuketou a paprikou, doplnený vajcami natvrdo.",
  ing:[i("Cícer",720,"g"),i("Vajcia",4,"ks"),i("Cuketa",400,"g"),i("Paprika červená",320,"g"),i("Olivový olej",32,"g"),i("Cesnak",12,"g"),i("Rasca",4,"g")],
  postup:["Predhrej rúru na 200 °C a nakrájaj cuketu a papriku na kocky.","Zmiešaj zeleninu so scedeným cícerom, olejom, cesnakom a rascou a peč 25 minút.","Uvar vajcia natvrdo, olúp ich, prekroj a poukladaj na pečený cícer."],
  tipy:"Cícer musí byť pred pečením suchý — mokrý sa dusí a nechrumká.",
  tagy:["hlavné jedlo","strukoviny","vláknina","vajcia","bezmäsité"] },

{ id:"morcacie-s-krupami-a-kapustou", nazov:"Morčacie mäso s krúpami a kapustou", kat:"Hlavné jedlo", kuchyna:"Slovenská", cas:"45 min", porcie:4, hlavna:"Krúpy", narocnost:"stredná",
  popis:"Jačmenné krúpy dusené s kyslou kapustou a morčacím mäsom.",
  ing:[i("Krúpy",240,"g"),i("Morčacia šunka",440,"g"),i("Kyslá kapusta",480,"g"),i("Cibuľa",160,"g"),i("Mrkva",240,"g"),i("Olivový olej",28,"g"),i("Rasca",4,"g")],
  postup:["Nakrájaj morčacie mäso na kocky a opeč ho na oleji.","Pridaj nasekanú cibuľu, nastrúhanú mrkvu a rascu a krátko orestuj.","Vsyp prepláchnuté krúpy s kyslou kapustou, zalej vodou a dus 30 minút."],
  tipy:"Kyslú kapustu pridávaj naraz s krúpami — kyselina im predĺži varenie, ale prevonia ich.",
  tagy:["hlavné jedlo","celozrnné","vláknina","mäso","slovenská"] },

{ id:"zeleninove-kari-s-cicerom-a-tofu", nazov:"Zeleninové kari s cícerom a tofu", kat:"Hlavné jedlo", kuchyna:"Indická", cas:"35 min", porcie:4, hlavna:"Cícer",
  popis:"Kari z cíceru, tofu, karfiolu a hrášku v kokosovom mlieku.",
  ing:[i("Cícer",640,"g"),i("Tofu",320,"g"),i("Karfiol",600,"g"),i("Zelený hrášok",240,"g"),i("Kokosové mlieko",200,"g"),i("Karí korenie",16,"g"),i("Cibuľa",160,"g")],
  postup:["Nakrájaj tofu na kocky a opeč ho na suchej panvici dozlatista.","Orestuj nasekanú cibuľu s karí korením a pridaj ružičky karfiolu.","Vmiešaj scedený cícer, hrášok a kokosové mlieko a dus 15 minút."],
  tipy:"Karfiol nechaj na skusmo pevný — v kari sa ešte dopečie vlastným teplom.",
  tagy:["hlavné jedlo","strukoviny","vláknina","bezmäsité","vysoký obsah bielkovín"] },

{ id:"celozrnne-cestoviny-s-hraskom-a-sunkou", nazov:"Celozrnné cestoviny s hráškom a šunkou", kat:"Cestoviny", kuchyna:"Talianska", cas:"25 min", porcie:4, hlavna:"Celozrnné cestoviny",
  popis:"Celozrnné cestoviny so zeleným hráškom, šunkou a cottage syrom.",
  ing:[i("Celozrnné cestoviny",240,"g"),i("Zelený hrášok",400,"g"),i("Šunka",240,"g"),i("Cottage syr",360,"g"),i("Cesnak",12,"g"),i("Olivový olej",20,"g")],
  postup:["Uvar cestoviny v osolenej vode a posledné tri minúty pridaj hrášok.","Nakrájaj šunku na prúžky a orestuj ju na oleji s cesnakom.","Vmiešaj scedené cestoviny s hráškom a cottage syrom a rozrieď vodou z varenia."],
  tipy:"Cottage syr sa v horúcich cestovinách roztopí na krémovú omáčku bez smotany.",
  tagy:["cestoviny","celozrnné","vláknina","mäso","vysoký obsah bielkovín"] },

{ id:"zapekana-cvikla-s-cicerom-a-fetou", nazov:"Zapekaná cvikla s cícerom a fetou", kat:"Hlavné jedlo", kuchyna:"Grécka", cas:"45 min", porcie:4, hlavna:"Cvikla", narocnost:"stredná",
  popis:"Cvikla a cícer pečené s fetou a tymianom.",
  ing:[i("Cvikla",800,"g"),i("Cícer",640,"g"),i("Feta",200,"g"),i("Cibuľa červená",200,"g"),i("Olivový olej",32,"g"),i("Tymian",4,"g"),i("Vlašské orechy",60,"g")],
  postup:["Predhrej rúru na 200 °C a nakrájaj varenú cviklu a cibuľu na kocky.","Zmiešaj cviklu so scedeným cícerom, olejom a tymianom a peč 25 minút.","Posyp rozdrobenou fetou a nasekanými orechmi a dopeč päť minút."],
  tipy:"Cviklu si uvar dopredu — surová sa v rúre pečie takmer hodinu.",
  tagy:["hlavné jedlo","strukoviny","vláknina","bezmäsité"] }
];
